@startuml

title __ENUMPDF's Class Diagram__\n

  namespace enumPdf {
    enum NameFieldsPdfCliente {
      CAPITALE_FIN
      CAP_ALTRA_CORRISPONDENZA
      CAP_AZIENDA
      CAP_CORRISPONDENZA
      CAP_DOMICILIO
      CAP_RESIDENZA
      CATEGORIA_PENSIONE
      CF
      CHECKBOX_ALTRA_CORRISPONDENZA
      CHECKBOX_CARTA_IDENTITA
      CHECKBOX_CQP
      CHECKBOX_CQS
      CHECKBOX_DIPENDENTE
      CHECKBOX_DLG
      CHECKBOX_DOMICILIO
      CHECKBOX_PASSAPORTO
      CHECKBOX_PATENTE
      CHECKBOX_PEC_NO
      CHECKBOX_PEC_SI
      CHECKBOX_PENSIONATO
      CHECKBOX_PP
      CHECKBOX_PRIVATO
      CHECKBOX_PUBBLICO
      CHECKBOX_QUOTA_CEDIBILE
      CHECKBOX_RESIDENZA
      CHECKBOX_STATALE
      CITTADINANZA
      CIVICO_ALTRA_CORRISPONDENZA
      CIVICO_DOMICILIO
      CIVICO_RESIDENZA
      COGNOME
      COGNOME_TITOLARE_AZIENDA
      COMUNIONE
      CONTEGGIO_EST
      CQP_LETTERE
      CQS_LETTERE
      DATA_APERTURA_CONTO
      DATA_CARICAMENTO
      DATA_CORRENTE
      DATA_DECORRENZA
      DATA_INIZIO_OCCUPAZIONE
      DATA_INIZIO_PENSIONE
      DATA_NASCITA
      DATA_RILASCIO_DOC
      DLG_LETTERE
      DURATA
      DURATA_CQ
      DURATA_DLG
      EMAIL
      EMAIL_AZIENDA
      ENTE_PENSIONISTICO
      EURO_PROVVIGIONI
      EURO_PROVVIGIONI_LETTERE
      FAX
      FAX_AZIENDA
      FEMMINA
      FILIALE
      FISSO
      GARANZIA
      IBAN
      ID_PRATICA
      IMPIEGO
      IMPORTO_EROGATO
      IMPORTO_EROGATO_LETTERE
      INDIRIZZO_ALTRA_CORRISPONDENZA
      INDIRIZZO_AZIENDA
      INDIRIZZO_CORRISPONDENZA
      INDIRIZZO_DOMICILIO
      INDIRIZZO_DOMICILIO_NO_CIVICO
      INDIRIZZO_RESIDENZA
      INDIRIZZO_RESIDENZA_NO_CIVICO
      INTERESSI
      INTERESSI_LETTERE
      ISTITUTO_EST
      LUOGO_ALTRA_CORRISPONDENZA
      LUOGO_AZIENDA
      LUOGO_CORRISPONDENZA
      LUOGO_DOMICILIO
      LUOGO_NASCITA
      LUOGO_RESIDENZA
      MASCHIO
      MONTANTE
      MONTANTE_LETTERE
      NETTO_MENSILE
      NETTO_RICAVO
      NOME
      NOME_AZIENDA
      NOME_COGNOME_OPERATORE
      NOME_TITOLARE_AZIENDA
      NOTE
      NOTE_PRATICA
      NUMERO_CTR
      NUMERO_DOC
      NUMERO_SECCI
      OCCUPAZIONE
      OPERATORE
      PEC_AZIENDA
      PERC_PROVVIGIONI
      PIVA
      PIVA_AZIENDA
      PP_LETTERE
      PROVINCIA_ALTRA_CORRISPONDENZA
      PROVINCIA_AZIENDA
      PROVINCIA_DOMICILIO
      PROVINCIA_RESIDENZA
      PROV_CORRISPONDENZA
      PROV_NASCITA
      RAGIONE_SOCIALE
      RATA
      RATA_EST
      RATA_SECONDA_EST
      REDDITO_ANNUO
      REFERENTE
      RILASCIO_DOC
      RUOLO
      SCADENZA_DOC
      SCADENZA_EST
      SECONDA_EST
      SEDE_LEGALE
      SEDE_NOTIFICA
      SEPARAZIONE
      SOTTOSCRITTO
      SPESE
      SPESE_LETTERE
      SPORTELLO
      STATO_CIVILE
      TAEG
      TAN
      TEG
      TELEFONO
      TELEFONO_AZIENDA
      TELEFONO_FISSO
      TIPO_DOC
      TIPO_PRATICA_LETTERE
      fieldName
    }
  }
  

  namespace enumPdf {
    enum NameFieldsPdfFattura {
      CF
      DATA_FATTURA
      DESCRIZIONE
      FATTURA_NUMERO
      FAX
      IMPONIBILE
      IMPORTO
      INDIRIZZO_CLIENTE
      IVA
      NOME_CLIENTE
      PIVA
      PREZZO_UNITARIO
      QUANTITA
      TELEFONO
      TOTALE_FATTURA
      fieldName
    }
  }
  

  namespace enumPdf {
    enum NameFieldsPdfNominativi {
      COGNOME
      DATA_CARICAMENTO
      DATA_NASCITA
      DATA_RECALL
      DATA_RINNOVO_TRATTENUTA_1
      DATA_RINNOVO_TRATTENUTA_2
      DATA_RINNOVO_TRATTENUTA_3
      DURATA_PREVENTIVO_1
      DURATA_PREVENTIVO_2
      DURATA_PREVENTIVO_3
      DURATA_TRATTENUTA_1
      DURATA_TRATTENUTA_2
      DURATA_TRATTENUTA_3
      ETA
      IMPIEGO
      IMPORTO_PREVENTIVO_1
      IMPORTO_PREVENTIVO_2
      IMPORTO_PREVENTIVO_3
      LUOGO_NASCITA
      MAIL
      NETTO_STIPENDIO
      NOME
      NOTE
      OPERATORE
      PROVENIENZA
      PROVENIENZA_DESC
      RATA_PREVENTIVO_1
      RATA_PREVENTIVO_2
      RATA_PREVENTIVO_3
      RATA_TRATTENUTA_1
      RATA_TRATTENUTA_2
      RATA_TRATTENUTA_3
      STATO_NOMINATIVO
      TELEFONO
      TIPO_PREVENTIVO_1
      TIPO_PREVENTIVO_2
      TIPO_PREVENTIVO_3
      TIPO_TRATTENUTA_1
      TIPO_TRATTENUTA_2
      TIPO_TRATTENUTA_3
      fieldName
    }
  }
  

  namespace enumPdf {
    enum PdfFileType {
      ALLEGATI
      ANAGRAFICA
      DEFAULT_TEMPLATE
      MARKETING
      PREFIN
      PRIVACY
      SCHEDA_ATC
      name
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
