@startuml

title __TENANTREPOSITORY's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace tenantrepository {
        class com.woonders.lacemscommon.db.tenantrepository.SmsTenant {
            - id : Long
            - idSms : String
            - tenantName : String
            + SmsTenant()
            + SmsTenant()
            {static} + builder()
            + getId()
            + getIdSms()
            + getTenantName()
            + setId()
            + setIdSms()
            + setTenantName()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace tenantrepository {
        class com.woonders.lacemscommon.db.tenantrepository.SmsTenant.SmsTenantBuilder {
            - id : Long
            - idSms : String
            - tenantName : String
            + build()
            + id()
            + idSms()
            + tenantName()
            + toString()
            ~ SmsTenantBuilder()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace tenantrepository {
        interface com.woonders.lacemscommon.db.tenantrepository.SmsTenantRepository {
            {abstract} + findAll()
            {abstract} + findByIdSms()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace tenantrepository {
        class com.woonders.lacemscommon.db.tenantrepository.Tenant {
            - enabled : boolean
            - id : long
            - name : String
            + Tenant()
            + Tenant()
            {static} + builder()
            + getId()
            + getName()
            + isEnabled()
            + setEnabled()
            + setId()
            + setName()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace tenantrepository {
        class com.woonders.lacemscommon.db.tenantrepository.Tenant.TenantBuilder {
            - enabled : boolean
            - id : long
            - name : String
            + build()
            + enabled()
            + id()
            + name()
            + toString()
            ~ TenantBuilder()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace tenantrepository {
        interface com.woonders.lacemscommon.db.tenantrepository.TenantRepository {
        }
      }
    }
  }
  

  com.woonders.lacemscommon.db.tenantrepository.SmsTenant +-down- com.woonders.lacemscommon.db.tenantrepository.SmsTenant.SmsTenantBuilder
  com.woonders.lacemscommon.db.tenantrepository.Tenant +-down- com.woonders.lacemscommon.db.tenantrepository.Tenant.TenantBuilder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
