@startuml

title __INVIAMAIL's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.request {
        namespace inviamail {
          class com.woonders.lacemscommon.fattureincloud.network.request.inviamail.InviaMailRequestBody {
              + allegaPdf : boolean
              + id : String
              + includiAllegato : boolean
              + includiDocumento : boolean
              + inviaCopia : boolean
              + inviaDdt : boolean
              + inviaFa : boolean
              + mailDestinatario : String
              + mailMittente : String
              + messaggio : String
              + oggetto : String
              + token : String
              + InviaMailRequestBody()
              + InviaMailRequestBody()
              {static} + builder()
              + getId()
              + getMailDestinatario()
              + getMailMittente()
              + getMessaggio()
              + getOggetto()
              + getToken()
              + isAllegaPdf()
              + isIncludiAllegato()
              + isIncludiDocumento()
              + isInviaCopia()
              + isInviaDdt()
              + isInviaFa()
              + setAllegaPdf()
              + setId()
              + setIncludiAllegato()
              + setIncludiDocumento()
              + setInviaCopia()
              + setInviaDdt()
              + setInviaFa()
              + setMailDestinatario()
              + setMailMittente()
              + setMessaggio()
              + setOggetto()
              + setToken()
              + toString()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.request {
        namespace inviamail {
          class com.woonders.lacemscommon.fattureincloud.network.request.inviamail.InviaMailRequestBody.InviaMailRequestBodyBuilder {
              - allegaPdf : boolean
              - id : String
              - includiAllegato : boolean
              - includiDocumento : boolean
              - inviaCopia : boolean
              - inviaDdt : boolean
              - inviaFa : boolean
              - mailDestinatario : String
              - mailMittente : String
              - messaggio : String
              - oggetto : String
              - token : String
              + allegaPdf()
              + build()
              + id()
              + includiAllegato()
              + includiDocumento()
              + inviaCopia()
              + inviaDdt()
              + inviaFa()
              + mailDestinatario()
              + mailMittente()
              + messaggio()
              + oggetto()
              + toString()
              + token()
              ~ InviaMailRequestBodyBuilder()
          }
        }
      }
    }
  }
  

  com.woonders.lacemscommon.fattureincloud.network.request.inviamail.InviaMailRequestBody -up-|> com.woonders.lacemscommon.fattureincloud.network.request.BaseRequestBody
  com.woonders.lacemscommon.fattureincloud.network.request.inviamail.InviaMailRequestBody +-down- com.woonders.lacemscommon.fattureincloud.network.request.inviamail.InviaMailRequestBody.InviaMailRequestBodyBuilder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
