@startuml

title __NEWDOC's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.request {
        namespace newdoc {
          class com.woonders.lacemscommon.fattureincloud.network.request.newdoc.Articolo {
              + applicaRaContributi : boolean
              + categoria : String
              + codIva : int
              + codice : String
              + descrizione : String
              + id : String
              + inDdt : boolean
              + magazzino : boolean
              + nome : String
              + ordine : int
              + prezzoLordo : BigDecimal
              + prezzoNetto : BigDecimal
              + quantita : BigDecimal
              + sconto : BigDecimal
              + scontoRosso : int
              + tassabile : boolean
              + unitaDiMisura : String
              + Articolo()
              + Articolo()
              {static} + builder()
              + getCategoria()
              + getCodIva()
              + getCodice()
              + getDescrizione()
              + getId()
              + getNome()
              + getOrdine()
              + getPrezzoLordo()
              + getPrezzoNetto()
              + getQuantita()
              + getSconto()
              + getScontoRosso()
              + getUnitaDiMisura()
              + isApplicaRaContributi()
              + isInDdt()
              + isMagazzino()
              + isTassabile()
              + setApplicaRaContributi()
              + setCategoria()
              + setCodIva()
              + setCodice()
              + setDescrizione()
              + setId()
              + setInDdt()
              + setMagazzino()
              + setNome()
              + setOrdine()
              + setPrezzoLordo()
              + setPrezzoNetto()
              + setQuantita()
              + setSconto()
              + setScontoRosso()
              + setTassabile()
              + setUnitaDiMisura()
              + toString()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.request {
        namespace newdoc {
          class com.woonders.lacemscommon.fattureincloud.network.request.newdoc.Articolo.ArticoloBuilder {
              - applicaRaContributi : boolean
              - categoria : String
              - codIva : int
              - codice : String
              - descrizione : String
              - id : String
              - inDdt : boolean
              - magazzino : boolean
              - nome : String
              - ordine : int
              - prezzoLordo : BigDecimal
              - prezzoNetto : BigDecimal
              - quantita : BigDecimal
              - sconto : BigDecimal
              - scontoRosso : int
              - tassabile : boolean
              - unitaDiMisura : String
              + applicaRaContributi()
              + build()
              + categoria()
              + codIva()
              + codice()
              + descrizione()
              + id()
              + inDdt()
              + magazzino()
              + nome()
              + ordine()
              + prezzoLordo()
              + prezzoNetto()
              + quantita()
              + sconto()
              + scontoRosso()
              + tassabile()
              + toString()
              + unitaDiMisura()
              ~ ArticoloBuilder()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.request {
        namespace newdoc {
          enum TipoArticolo {
            SMS1V1
            SMS2V1
            SMS3V1
            SMS4V1
            SMS5V1
            PACCHETTO_SMS
            amount
            id
            prezzoLordo
            smsQuantity
            smsUnitCost
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.request {
        namespace newdoc {
          class com.woonders.lacemscommon.fattureincloud.network.request.newdoc.ExtraAnagrafica {
              + fax : String
              + mail : String
              + tel : String
              + ExtraAnagrafica()
              + ExtraAnagrafica()
              {static} + builder()
              + getFax()
              + getMail()
              + getTel()
              + setFax()
              + setMail()
              + setTel()
              + toString()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.request {
        namespace newdoc {
          class com.woonders.lacemscommon.fattureincloud.network.request.newdoc.ExtraAnagrafica.ExtraAnagraficaBuilder {
              - fax : String
              - mail : String
              - tel : String
              + build()
              + fax()
              + mail()
              + tel()
              + toString()
              ~ ExtraAnagraficaBuilder()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.request {
        namespace newdoc {
          class com.woonders.lacemscommon.fattureincloud.network.request.newdoc.NewDocRequestBody {
              + autocompilaAnagrafica : boolean
              + centroCosto : String
              + centroRicavo : String
              + cf : String
              + data : Date
              + ddtAnnotazioni : String
              + ddtCausale : String
              + ddtColli : String
              + ddtData : Date
              + ddtIdTemplate : String
              + ddtLuogo : String
              + ddtNumero : String
              + ddtPeso : String
              + ddtTrasportatore : String
              + existDDT : boolean
              + existFatturaAccompagnatoria : boolean
              + ftaccIdTemplate : String
              + idCliente : String
              + idFornitore : String
              + idTemplate : String
              + indirizzoCap : String
              + indirizzoCitta : String
              + indirizzoExtra : String
              + indirizzoProvincia : String
              + indirizzoVia : String
              + lingua : String
              + listaArticoli : List<Articolo>
              + listaPagamenti : List<Pagamento>
              + marcaBollo : BigDecimal
              + metodoDescN : String
              + metodoPagamento : String
              + metodoTitoloN : String
              + mostraBottoneBonifico : boolean
              + mostraBottoneNotifica : boolean
              + mostraBottonePaypal : boolean
              + mostraInfoPagamento : boolean
              + mostraTotali : String
              + nascondiScadenza : boolean
              + nome : String
              + note : String
              + numero : String
              + oggettoInterno : String
              + oggettoVisibile : String
              + pA : boolean
              + pABeneficiario : String
              + pACodice : String
              + pACodiceUnitarioProgetto : String
              + pAData : Date
              + pAEsigibilita : String
              + pAIban : String
              + pAIstitutoCredito : String
              + pAModalitaPagamento : String
              + pANumero : String
              + pAPec : String
              + pATipo : String
              + pATipoCliente : String
              + paCodiceIdentificativoGara : String
              + paese : String
              + paeseIso : String
              + percentualeAltrRitenuta : BigDecimal
              + percentualeCassaPrevidenziale : BigDecimal
              + percentualeImponibileRitenuta : BigDecimal
              + percentualeRitenutaAcconto : BigDecimal
              + piva : String
              + prezziIvati : boolean
              + rivalsa : BigDecimal
              + salvaAnagrafica : boolean
              + valuta : String
              + valutaCambio : BigDecimal
              + NewDocRequestBody()
              + NewDocRequestBody()
              {static} + builder()
              + getCentroCosto()
              + getCentroRicavo()
              + getCf()
              + getData()
              + getDdtAnnotazioni()
              + getDdtCausale()
              + getDdtColli()
              + getDdtData()
              + getDdtIdTemplate()
              + getDdtLuogo()
              + getDdtNumero()
              + getDdtPeso()
              + getDdtTrasportatore()
              + getExtraAnagrafica()
              + getFtaccIdTemplate()
              + getIdCliente()
              + getIdFornitore()
              + getIdTemplate()
              + getIndirizzoCap()
              + getIndirizzoCitta()
              + getIndirizzoExtra()
              + getIndirizzoProvincia()
              + getIndirizzoVia()
              + getLingua()
              + getListaArticoli()
              + getListaPagamenti()
              + getMarcaBollo()
              + getMetodoDescN()
              + getMetodoPagamento()
              + getMetodoTitoloN()
              + getMostraTotali()
              + getNome()
              + getNote()
              + getNumero()
              + getOggettoInterno()
              + getOggettoVisibile()
              + getPABeneficiario()
              + getPACodice()
              + getPACodiceUnitarioProgetto()
              + getPAData()
              + getPAEsigibilita()
              + getPAIban()
              + getPAIstitutoCredito()
              + getPAModalitaPagamento()
              + getPANumero()
              + getPAPec()
              + getPATipo()
              + getPATipoCliente()
              + getPaCodiceIdentificativoGara()
              + getPaese()
              + getPaeseIso()
              + getPercentualeAltrRitenuta()
              + getPercentualeCassaPrevidenziale()
              + getPercentualeImponibileRitenuta()
              + getPercentualeRitenutaAcconto()
              + getPiva()
              + getRivalsa()
              + getValuta()
              + getValutaCambio()
              + isAutocompilaAnagrafica()
              + isExistDDT()
              + isExistFatturaAccompagnatoria()
              + isMostraBottoneBonifico()
              + isMostraBottoneNotifica()
              + isMostraBottonePaypal()
              + isMostraInfoPagamento()
              + isNascondiScadenza()
              + isPA()
              + isPrezziIvati()
              + isSalvaAnagrafica()
              + setAutocompilaAnagrafica()
              + setCentroCosto()
              + setCentroRicavo()
              + setCf()
              + setData()
              + setDdtAnnotazioni()
              + setDdtCausale()
              + setDdtColli()
              + setDdtData()
              + setDdtIdTemplate()
              + setDdtLuogo()
              + setDdtNumero()
              + setDdtPeso()
              + setDdtTrasportatore()
              + setExistDDT()
              + setExistFatturaAccompagnatoria()
              + setExtraAnagrafica()
              + setFtaccIdTemplate()
              + setIdCliente()
              + setIdFornitore()
              + setIdTemplate()
              + setIndirizzoCap()
              + setIndirizzoCitta()
              + setIndirizzoExtra()
              + setIndirizzoProvincia()
              + setIndirizzoVia()
              + setLingua()
              + setListaArticoli()
              + setListaPagamenti()
              + setMarcaBollo()
              + setMetodoDescN()
              + setMetodoPagamento()
              + setMetodoTitoloN()
              + setMostraBottoneBonifico()
              + setMostraBottoneNotifica()
              + setMostraBottonePaypal()
              + setMostraInfoPagamento()
              + setMostraTotali()
              + setNascondiScadenza()
              + setNome()
              + setNote()
              + setNumero()
              + setOggettoInterno()
              + setOggettoVisibile()
              + setPA()
              + setPABeneficiario()
              + setPACodice()
              + setPACodiceUnitarioProgetto()
              + setPAData()
              + setPAEsigibilita()
              + setPAIban()
              + setPAIstitutoCredito()
              + setPAModalitaPagamento()
              + setPANumero()
              + setPAPec()
              + setPATipo()
              + setPATipoCliente()
              + setPaCodiceIdentificativoGara()
              + setPaese()
              + setPaeseIso()
              + setPercentualeAltrRitenuta()
              + setPercentualeCassaPrevidenziale()
              + setPercentualeImponibileRitenuta()
              + setPercentualeRitenutaAcconto()
              + setPiva()
              + setPrezziIvati()
              + setRivalsa()
              + setSalvaAnagrafica()
              + setValuta()
              + setValutaCambio()
              + toString()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.request {
        namespace newdoc {
          class com.woonders.lacemscommon.fattureincloud.network.request.newdoc.NewDocRequestBody.NewDocRequestBodyBuilder {
              - autocompilaAnagrafica : boolean
              - centroCosto : String
              - centroRicavo : String
              - cf : String
              - data : Date
              - ddtAnnotazioni : String
              - ddtCausale : String
              - ddtColli : String
              - ddtData : Date
              - ddtIdTemplate : String
              - ddtLuogo : String
              - ddtNumero : String
              - ddtPeso : String
              - ddtTrasportatore : String
              - existDDT : boolean
              - existFatturaAccompagnatoria : boolean
              - ftaccIdTemplate : String
              - idCliente : String
              - idFornitore : String
              - idTemplate : String
              - indirizzoCap : String
              - indirizzoCitta : String
              - indirizzoExtra : String
              - indirizzoProvincia : String
              - indirizzoVia : String
              - lingua : String
              - listaArticoli : List<Articolo>
              - listaPagamenti : List<Pagamento>
              - marcaBollo : BigDecimal
              - metodoDescN : String
              - metodoPagamento : String
              - metodoTitoloN : String
              - mostraBottoneBonifico : boolean
              - mostraBottoneNotifica : boolean
              - mostraBottonePaypal : boolean
              - mostraInfoPagamento : boolean
              - mostraTotali : String
              - nascondiScadenza : boolean
              - nome : String
              - note : String
              - numero : String
              - oggettoInterno : String
              - oggettoVisibile : String
              - pA : boolean
              - pABeneficiario : String
              - pACodice : String
              - pACodiceUnitarioProgetto : String
              - pAData : Date
              - pAEsigibilita : String
              - pAIban : String
              - pAIstitutoCredito : String
              - pAModalitaPagamento : String
              - pANumero : String
              - pAPec : String
              - pATipo : String
              - pATipoCliente : String
              - paCodiceIdentificativoGara : String
              - paese : String
              - paeseIso : String
              - percentualeAltrRitenuta : BigDecimal
              - percentualeCassaPrevidenziale : BigDecimal
              - percentualeImponibileRitenuta : BigDecimal
              - percentualeRitenutaAcconto : BigDecimal
              - piva : String
              - prezziIvati : boolean
              - rivalsa : BigDecimal
              - salvaAnagrafica : boolean
              - valuta : String
              - valutaCambio : BigDecimal
              + autocompilaAnagrafica()
              + build()
              + centroCosto()
              + centroRicavo()
              + cf()
              + data()
              + ddtAnnotazioni()
              + ddtCausale()
              + ddtColli()
              + ddtData()
              + ddtIdTemplate()
              + ddtLuogo()
              + ddtNumero()
              + ddtPeso()
              + ddtTrasportatore()
              + existDDT()
              + existFatturaAccompagnatoria()
              + extraAnagrafica()
              + ftaccIdTemplate()
              + idCliente()
              + idFornitore()
              + idTemplate()
              + indirizzoCap()
              + indirizzoCitta()
              + indirizzoExtra()
              + indirizzoProvincia()
              + indirizzoVia()
              + lingua()
              + listaArticoli()
              + listaPagamenti()
              + marcaBollo()
              + metodoDescN()
              + metodoPagamento()
              + metodoTitoloN()
              + mostraBottoneBonifico()
              + mostraBottoneNotifica()
              + mostraBottonePaypal()
              + mostraInfoPagamento()
              + mostraTotali()
              + nascondiScadenza()
              + nome()
              + note()
              + numero()
              + oggettoInterno()
              + oggettoVisibile()
              + pA()
              + pABeneficiario()
              + pACodice()
              + pACodiceUnitarioProgetto()
              + pAData()
              + pAEsigibilita()
              + pAIban()
              + pAIstitutoCredito()
              + pAModalitaPagamento()
              + pANumero()
              + pAPec()
              + pATipo()
              + pATipoCliente()
              + paCodiceIdentificativoGara()
              + paese()
              + paeseIso()
              + percentualeAltrRitenuta()
              + percentualeCassaPrevidenziale()
              + percentualeImponibileRitenuta()
              + percentualeRitenutaAcconto()
              + piva()
              + prezziIvati()
              + rivalsa()
              + salvaAnagrafica()
              + toString()
              + valuta()
              + valutaCambio()
              ~ NewDocRequestBodyBuilder()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.request {
        namespace newdoc {
          class com.woonders.lacemscommon.fattureincloud.network.request.newdoc.Pagamento {
              + dataSaldo : LocalDate
              + dataScadenza : LocalDate
              + importo : String
              + metodo : String
              + Pagamento()
              + Pagamento()
              {static} + builder()
              + getDataSaldo()
              + getDataScadenza()
              + getImporto()
              + getMetodo()
              + setDataSaldo()
              + setDataScadenza()
              + setImporto()
              + setMetodo()
              + toString()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.request {
        namespace newdoc {
          class com.woonders.lacemscommon.fattureincloud.network.request.newdoc.Pagamento.PagamentoBuilder {
              - dataSaldo : LocalDate
              - dataScadenza : LocalDate
              - importo : String
              - metodo : String
              + build()
              + dataSaldo()
              + dataScadenza()
              + importo()
              + metodo()
              + toString()
              ~ PagamentoBuilder()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.request {
        namespace newdoc {
          enum Tipo {
            STRIPE
            value
          }
        }
      }
    }
  }
  

  com.woonders.lacemscommon.fattureincloud.network.request.newdoc.Articolo .up.|> java.io.Serializable
  com.woonders.lacemscommon.fattureincloud.network.request.newdoc.Articolo +-down- com.woonders.lacemscommon.fattureincloud.network.request.newdoc.Articolo.ArticoloBuilder
  com.woonders.lacemscommon.fattureincloud.network.request.newdoc.Articolo +-down- com.woonders.lacemscommon.fattureincloud.network.request.newdoc.Articolo.TipoArticolo
  com.woonders.lacemscommon.fattureincloud.network.request.newdoc.ExtraAnagrafica .up.|> java.io.Serializable
  com.woonders.lacemscommon.fattureincloud.network.request.newdoc.ExtraAnagrafica +-down- com.woonders.lacemscommon.fattureincloud.network.request.newdoc.ExtraAnagrafica.ExtraAnagraficaBuilder
  com.woonders.lacemscommon.fattureincloud.network.request.newdoc.NewDocRequestBody -up-|> com.woonders.lacemscommon.fattureincloud.network.request.BaseRequestBody
  com.woonders.lacemscommon.fattureincloud.network.request.newdoc.NewDocRequestBody o-- com.woonders.lacemscommon.fattureincloud.network.request.newdoc.ExtraAnagrafica : extraAnagrafica
  com.woonders.lacemscommon.fattureincloud.network.request.newdoc.NewDocRequestBody +-down- com.woonders.lacemscommon.fattureincloud.network.request.newdoc.NewDocRequestBody.NewDocRequestBodyBuilder
  com.woonders.lacemscommon.fattureincloud.network.request.newdoc.NewDocRequestBody.NewDocRequestBodyBuilder o-- com.woonders.lacemscommon.fattureincloud.network.request.newdoc.ExtraAnagrafica : extraAnagrafica
  com.woonders.lacemscommon.fattureincloud.network.request.newdoc.Pagamento .up.|> java.io.Serializable
  com.woonders.lacemscommon.fattureincloud.network.request.newdoc.Pagamento +-down- com.woonders.lacemscommon.fattureincloud.network.request.newdoc.Pagamento.PagamentoBuilder
  com.woonders.lacemscommon.fattureincloud.network.request.newdoc.Pagamento +-down- com.woonders.lacemscommon.fattureincloud.network.request.newdoc.Pagamento.Tipo


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
