FROM maven:3.8.3-openjdk as build

WORKDIR /app

COPY ./pom.xml ./
#COPY ../lacems-common/src ./src
RUN mvn -f pom.xml clean package

#FROM adoptopenjdk/maven-openjdk12:latest

#WORKDIR /app

#COPY pom.xml ./

#RUN mvn dependency:go-offline
#RUN mvn dependency:resolve-plugins