@startuml

title __REPOSITORY's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.AccessLogRepository {
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.AmministrazioneRepository {
            {abstract} + findByCodiceFiscaleIgnoreCase()
            {abstract} + findByPivaIgnoreCase()
            {abstract} + findByRagioneSocialeIgnoreCase()
            {abstract} + findDistinctByCliente_Id()
            {abstract} + findDistinctByRagioneSocialeContainingIgnoreCase()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.AziendaRepository {
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.BackupRepository {
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.CalendarioAppuntamentoRepository {
            {abstract} + findByNominativo_IdAndPratica_CodicePraticaIsNull()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.CampagnaRepository {
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.CampagnaSmsRepository {
            {abstract} + findByCampagnaIdAndEsitoIn()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.ClientePraticaFileRepository {
            {abstract} + findByCliente_Id()
            {abstract} + findByPratica_CodicePratica()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.ClienteRepository {
            {abstract} + countByCognomeAndNomeAndTelefono()
            {abstract} + deleteByCfIgnoreCaseAndTipoIgnoreCase()
            {abstract} + findByCfIgnoreCase()
            {abstract} + findByCfIgnoreCaseAndTipoIgnoreCase()
            {abstract} + findByCognomeAndNomeAndTelefono()
            {abstract} + findById()
            {abstract} + findByLeadId()
            {abstract} + findByPratica_CodicePratica()
            {abstract} + findByTipo()
            {abstract} + findDistinctByCf()
            {abstract} + findDistinctByCfAndTipo()
            {abstract} + findDistinctByCfAndTipoAndPratica_Operatore_Id()
            {abstract} + findDistinctByCognome()
            {abstract} + findDistinctByStatoNominativoAndTipo()
            {abstract} + findDistinctByStatoNominativoAndTipoAndOperatoreNominativo()
            {abstract} + findDistinctByTelefonoContainingOrTelefonoFissoContaining()
            {abstract} + findDistinctByTipoAndDataInsBetween()
            {abstract} + findDistinctByTipoAndOperatoreNominativo_UsernameAndDataInsBetween()
            {abstract} + findDistinctByTipoAndStatoNominativoAndDataInsBetween()
            {abstract} + findDistinctByTipoAndStatoNominativoAndOperatoreNominativo_UsernameAndDataInsBetween()
            {abstract} + getAllFornitoriLead()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.ContoRepository {
            {abstract} + findDistinctByCliente_Id()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.CoobbligatoRepository {
            {abstract} + findDistinctByPratica_CodicePratica()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.DocumentoRepository {
            {abstract} + findDistinctByCliente_Id()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.EstinzioneRepository {
            {abstract} + findDistinctByPratica_CodicePratica()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.FinanziariaRepository {
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.GeneralSettingRepository {
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.InfoAccountRepository {
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.NominativoLogRepository {
            {abstract} + findTopByNominativo_IdOrderByExecutionDateTimeDesc()
            {abstract} + findTopByPratica_CodicePraticaOrderByExecutionDateTimeDesc()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.NoticeBoardRepository {
            {abstract} + countByOperatorSetNotContaining()
            {abstract} + countByOperatorSetNotContainingAndAziendaAssigned_Id()
            {abstract} + countByOperatorSetNotContainingAndId()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.NotificaLeadSmsRepository {
            {abstract} + findByCliente_Id()
            {abstract} + findBySmsId()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.OperatorRepository {
            {abstract} + findByAzienda_Id()
            {abstract} + findByReceiveLeadEnabledTrueAndAzienda_Id()
            {abstract} + findByRole()
            {abstract} + findByRoleNotIn()
            {abstract} + findByRole_RoleName()
            {abstract} + findByUsername()
            {abstract} + findByUsernameAndPassword()
            {abstract} + findEmailByUsername()
            {abstract} + findTop1ByReceiveLeadEnabledTrueAndAzienda_IdOrderByLeadRicevutiAsc()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.PraticaRepository {
            {abstract} + findByNrctrEquals()
            {abstract} + findDistinctByCliente_Id()
            {abstract} + findDistinctByCliente_IdAndOperatore_Id()
            {abstract} + findDistinctByCliente_IdAndRinnovataFalseAndOrDecorrenzaNullOrScadenzaAndNotInStatoPratica()
            {abstract} + findDistinctByCliente_IdAndStatoPraticaNotInAndRinnovata()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.PreferenzaRepository {
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.PreferenzaStatoPraticaRepository {
            {abstract} + findByAzienda_Id()
            {abstract} + findByNomeStatoPraticaAndAzienda_Id()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.PreventivoRepository {
            {abstract} + findDistinctByCliente_IdAndCliente_Tipo()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.ResidenzaRepository {
            {abstract} + findDistinctByCliente_Id()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.RicaricaComunicazioneRepository {
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.RoleRepository {
            {abstract} + findByRoleName()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.SettingRepository {
            {abstract} + findByAzienda_Id()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.SimulatorTableDetailsRepository {
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.SimulatorTableRepository {
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.TrattenuteRepository {
            {abstract} + findDistinctByCliente_Id()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace repository {
        interface com.woonders.lacemscommon.db.repository.ValutazioneAmministrazioneRepository {
            {abstract} + findDistinctByAmministrazione_CodiceAmm()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
