@startuml

title __REQUEST's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace app.clicksend.model.request {
      class com.woonders.lacemscommon.app.clicksend.model.request.SendSmsRequest {
          ~ smsRequestList : List<SmsRequest>
          + SendSmsRequest()
          + SendSmsRequest()
          {static} + builder()
          + getSmsRequestList()
          + setSmsRequestList()
          + toString()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.clicksend.model.request {
      class com.woonders.lacemscommon.app.clicksend.model.request.SendSmsRequest.SendSmsRequestBuilder {
          - smsRequestList : List<SmsRequest>
          + build()
          + smsRequestList()
          + toString()
          ~ SendSmsRequestBuilder()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.clicksend.model.request {
      class com.woonders.lacemscommon.app.clicksend.model.request.SmsRequest {
          - body : String
          - country : String
          - customString : String
          - from : String
          - fromEmail : String
          - listId : long
          - schedule : long
          - source : String
          - to : String
          + SmsRequest()
          + SmsRequest()
          {static} + builder()
          + getBody()
          + getCountry()
          + getCustomString()
          + getFrom()
          + getFromEmail()
          + getListId()
          + getSchedule()
          + getSource()
          + getTo()
          + setBody()
          + setCountry()
          + setCustomString()
          + setFrom()
          + setFromEmail()
          + setListId()
          + setSchedule()
          + setSource()
          + setTo()
          + toString()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.clicksend.model.request {
      class com.woonders.lacemscommon.app.clicksend.model.request.SmsRequest.SmsRequestBuilder {
          - body : String
          - country : String
          - customString : String
          - from : String
          - fromEmail : String
          - listId : long
          - schedule : long
          - source : String
          - to : String
          + body()
          + build()
          + country()
          + customString()
          + from()
          + fromEmail()
          + listId()
          + schedule()
          + source()
          + to()
          + toString()
          ~ SmsRequestBuilder()
      }
    }
  }
  

  com.woonders.lacemscommon.app.clicksend.model.request.SendSmsRequest +-down- com.woonders.lacemscommon.app.clicksend.model.request.SendSmsRequest.SendSmsRequestBuilder
  com.woonders.lacemscommon.app.clicksend.model.request.SmsRequest +-down- com.woonders.lacemscommon.app.clicksend.model.request.SmsRequest.SmsRequestBuilder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
