package com.woonders.lacemsjsf.ui;

/**
 * Created by Emanuele on 19/06/2017.
 */
public enum AppMenuSection {

    //TODO DA RIMUOVERE GLI AFTER_SEARCH QUANDO SI RIFA IL LAYOUT!!!!!!!!
    DATI_AZIENDA, PREFERENZE, DASHBOARD, CALENDARIO, CAMPAGNE_MARKETING, NOMINATIVI, CLIENTI, CERCA, FATTURAZIONE, FATTURAZIONE_AFTER_SEARCH,
    AMMINISTRAZIONI, ANTI_RICICLAGGIO, ANTIRICICLAGGIO_AFTER_SEARCH, GESTIONE_PERMESSI, RICARICA, SIMULATORI_NEW, SIMULATORI_LIST,
    SIMULATORI_RUN, STATO_PRATICA, NOTICE_BOARD_ADD, NOTICE_BOARD_LIST, ACCESS_LOG

}
