@startuml

title __ELIMINADOC's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.request {
        namespace eliminadoc {
          class com.woonders.lacemscommon.fattureincloud.network.request.eliminadoc.EliminaDocRequestBody {
              + id : String
              + token : String
              + EliminaDocRequestBody()
              + EliminaDocRequestBody()
              {static} + builder()
              + getId()
              + getToken()
              + setId()
              + setToken()
              + toString()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.request {
        namespace eliminadoc {
          class com.woonders.lacemscommon.fattureincloud.network.request.eliminadoc.EliminaDocRequestBody.EliminaDocRequestBodyBuilder {
              - id : String
              - token : String
              + build()
              + id()
              + toString()
              + token()
              ~ EliminaDocRequestBodyBuilder()
          }
        }
      }
    }
  }
  

  com.woonders.lacemscommon.fattureincloud.network.request.eliminadoc.EliminaDocRequestBody -up-|> com.woonders.lacemscommon.fattureincloud.network.request.BaseRequestBody
  com.woonders.lacemscommon.fattureincloud.network.request.eliminadoc.EliminaDocRequestBody +-down- com.woonders.lacemscommon.fattureincloud.network.request.eliminadoc.EliminaDocRequestBody.EliminaDocRequestBodyBuilder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
