@startuml

title __FATTUREINCLOUD's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      class com.woonders.lacemscommon.fattureincloud.FattureInCloudClient {
          {static} - API_KEY : String
          {static} - API_KEY_NAME : String
          {static} - API_UID : String
          {static} - API_UID_NAME : String
          {static} - DETTAGLI_FATTURA_URL : String
          {static} - ELIMINA_FATTURA_URL : String
          {static} - FATTURE_IN_CLOUD_BASE_URL : String
          {static} - FATTURE_URL : String
          {static} - INVIA_FATTURA_URL : String
          {static} - NEW_FATTURE_URL : String
          + createNewDoc()
          + eliminaFattura()
          + getDettagliFattura()
          + init()
          + inviaMailFattura()
          # addAuthorization()
          - addAuthorizationToBody()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      enum FattureInCloudErrorCode {
        ACCESSO_NEGATO
        API_BLOCCATE
        AUTENTICAZIONE_FALLITA
        AZIENDA_INESISTENTE_O_DISABILITATA
        CONTENUTO_RICHIESTA_NON_CORRETTO
        ERRORE_GENERICO
        FUNZIONE_NON_CONSENTITA
        LICENZA_SCADUTA
        LIMITE_MAX_DOCUMENTI
        LIMITE_RICHIESTE_SUPERATO
        PARAMETRO_MANCANTE_O_INVALIDO
        TOTALE_CALCOLATO_NON_CORRISPONDENTE
        value
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      enum TipoDocumento {
        FATTURE
        value
      }
    }
  }
  

  com.woonders.lacemscommon.fattureincloud.FattureInCloudClient -up-|> com.woonders.lacemscommon.network.BaseClient
  com.woonders.lacemscommon.fattureincloud.FattureInCloudClient +-down- com.woonders.lacemscommon.fattureincloud.FattureInCloudClient.FattureInCloudErrorCode
  com.woonders.lacemscommon.fattureincloud.FattureInCloudClient +-down- com.woonders.lacemscommon.fattureincloud.FattureInCloudClient.TipoDocumento


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
