@startuml

title __BIGDECIMAL's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace app.model {
      namespace util {
        namespace bigdecimal {
          class com.woonders.lacemscommon.app.model.util.bigdecimal.BigDecimalUtils {
              {static} + is()
              {static} + is()
              - BigDecimalUtils()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      namespace util {
        namespace bigdecimal {
          class com.woonders.lacemscommon.app.model.util.bigdecimal.BigDecimalWrapper {
              {static} - ZERO : int
              - bigDecimal : BigDecimal
              + eq()
              + eq()
              + gt()
              + gt()
              + gte()
              + gte()
              + isNegative()
              + isNonNegative()
              + isNonPositive()
              + isNotZero()
              + isNullOrZero()
              + isPositive()
              + isZero()
              + lt()
              + lt()
              + lte()
              + lte()
              + notEq()
              + notEq()
              + notGt()
              + notGt()
              + notGte()
              + notGte()
              + notLt()
              + notLt()
              + notLte()
              + notLte()
              + notNullOrZero()
              ~ BigDecimalWrapper()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
