@startuml

title __CREATOR's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        abstract class com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator {
            + createModelList()
            + createModelList()
            + createViewModelList()
            + createViewModelList()
            + fromList()
            + fromModelList()
            + fromSet()
            + fromViewModelList()
            # trimIfNotNull()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.AccessLogViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.AmministrazioneViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.AziendaViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.BackupViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        interface com.woonders.lacemscommon.app.viewmodel.creator.BaseViewModelCreator {
            {abstract} + createModel()
            {abstract} + createModelList()
            {abstract} + createModelList()
            {abstract} + createViewModel()
            {abstract} + createViewModelList()
            {abstract} + createViewModelList()
            {abstract} + fromList()
            {abstract} + fromModelList()
            {abstract} + fromSet()
            {abstract} + fromViewModelList()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.CalendarioAppuntamentoViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.CampagnaSmsViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.CampagnaViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.ClientePraticaFileViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.ClienteViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.ContoViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.CoobbligatoViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.DocumentoViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.EstinzioneViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.FinanziariaViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.GeneralSettingViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.InfoAccountViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.NominativoLogViewModelCreator {
            {static} + MAX_COMMENT_LENGTH : int
            + createModel()
            + createViewModel()
            - generateShortComment()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.NoticeBoardViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.NotificaLeadSmsViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.OperatorViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.PraticaViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.PreferenzaStatoPraticaViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.PreventivoViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.ResidenzaViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.RicaricaComunicazioneViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.RoleViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.SettingViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.SimulatorTableDetailsViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.SimulatorTableViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.TrattenuteViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.viewmodel {
      namespace creator {
        class com.woonders.lacemscommon.app.viewmodel.creator.ValutazioneAmministrazioneViewModelCreator {
            + createModel()
            + createViewModel()
        }
      }
    }
  }
  

  com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator .up.|> com.woonders.lacemscommon.app.viewmodel.creator.BaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.AccessLogViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.AccessLogViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.OperatorViewModelCreator : operatorViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.AmministrazioneViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.AmministrazioneViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.ValutazioneAmministrazioneViewModelCreator : valutazioneAmministrazioneViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.AziendaViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.BackupViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.CalendarioAppuntamentoViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.CalendarioAppuntamentoViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.ClienteViewModelCreator : clienteViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.CalendarioAppuntamentoViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.OperatorViewModelCreator : operatorViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.CalendarioAppuntamentoViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.PraticaViewModelCreator : praticaViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.CampagnaSmsViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.CampagnaSmsViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.CampagnaViewModelCreator : campagnaViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.CampagnaSmsViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.ClienteViewModelCreator : clienteViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.CampagnaViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.CampagnaViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.OperatorViewModelCreator : operatorViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.ClientePraticaFileViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.ClienteViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.ClienteViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.AmministrazioneViewModelCreator : amministrazioneViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.ClienteViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.ClientePraticaFileViewModelCreator : clientePraticaFileViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.ClienteViewModelCreator o-- com.woonders.lacemscommon.db.entityutil.ClienteUtil : clienteUtil
  com.woonders.lacemscommon.app.viewmodel.creator.ClienteViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.ContoViewModelCreator : contoViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.ClienteViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.DocumentoViewModelCreator : documentoViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.ClienteViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.OperatorViewModelCreator : operatorViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.ClienteViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.PraticaViewModelCreator : praticaViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.ClienteViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.PreventivoViewModelCreator : preventivoViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.ClienteViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.ResidenzaViewModelCreator : residenzaViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.ClienteViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.TrattenuteViewModelCreator : trattenutaViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.ContoViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.CoobbligatoViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.DocumentoViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.EstinzioneViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.EstinzioneViewModelCreator o-- com.woonders.lacemscommon.db.entityutil.EstinzioneUtil : estinzioneUtil
  com.woonders.lacemscommon.app.viewmodel.creator.FinanziariaViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.GeneralSettingViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.InfoAccountViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.NominativoLogViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.NominativoLogViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.ClienteViewModelCreator : clienteViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.NominativoLogViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.OperatorViewModelCreator : operatorViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.NominativoLogViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.PraticaViewModelCreator : praticaViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.NoticeBoardViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.NoticeBoardViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.AziendaViewModelCreator : aziendaViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.NoticeBoardViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.OperatorViewModelCreator : operatorViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.NotificaLeadSmsViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.OperatorViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.OperatorViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.AziendaViewModelCreator : aziendaViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.OperatorViewModelCreator o-- com.woonders.lacemscommon.db.repository.RoleRepository : roleRepository
  com.woonders.lacemscommon.app.viewmodel.creator.OperatorViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.RoleViewModelCreator : roleViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.PraticaViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.PraticaViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.ClientePraticaFileViewModelCreator : clientePraticaFileViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.PraticaViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.CoobbligatoViewModelCreator : coobbligatoViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.PraticaViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.EstinzioneViewModelCreator : estinzioneViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.PraticaViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.FinanziariaViewModelCreator : finanziariaViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.PraticaViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.OperatorViewModelCreator : operatorViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.PraticaViewModelCreator o-- com.woonders.lacemscommon.db.entityutil.PraticaUtil : praticaUtil
  com.woonders.lacemscommon.app.viewmodel.creator.PraticaViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.SimulatorTableViewModelCreator : simulatorTableViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.PraticaViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.converter.StringAndBigDecimalConverter : stringAndBigDecimalConverter
  com.woonders.lacemscommon.app.viewmodel.creator.PreferenzaStatoPraticaViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.PreferenzaStatoPraticaViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.AziendaViewModelCreator : aziendaViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.PreventivoViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.PreventivoViewModelCreator o-- com.woonders.lacemscommon.db.entityutil.PreventivoUtil : preventivoUtil
  com.woonders.lacemscommon.app.viewmodel.creator.PreventivoViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.SimulatorTableViewModelCreator : simulatorTableViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.ResidenzaViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.RicaricaComunicazioneViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.RicaricaComunicazioneViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.OperatorViewModelCreator : operatorViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.RoleViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.SettingViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.SettingViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.AziendaViewModelCreator : aziendaViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.SimulatorTableDetailsViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.SimulatorTableDetailsViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.SimulatorTableViewModelCreator : simulatorTableViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.SimulatorTableViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.SimulatorTableViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.AziendaViewModelCreator : aziendaViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.SimulatorTableViewModelCreator o-- com.woonders.lacemscommon.app.viewmodel.creator.OperatorViewModelCreator : operatorViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.TrattenuteViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator
  com.woonders.lacemscommon.app.viewmodel.creator.TrattenuteViewModelCreator o-- com.woonders.lacemscommon.db.entityutil.TrattenutaUtil : trattenutaUtil
  com.woonders.lacemscommon.app.viewmodel.creator.ValutazioneAmministrazioneViewModelCreator -up-|> com.woonders.lacemscommon.app.viewmodel.creator.AbstractBaseViewModelCreator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
