@startuml

title __MENU's Class Diagram__\n

  namespace org.primefaces.ultima.component.menu {
    class org.primefaces.ultima.component.menu.UltimaMenu {
        {static} + COMPONENT_FAMILY : String
        {static} + COMPONENT_TYPE : String
        {static} - DEFAULT_RENDERER : String
        {static} - LEGACY_RESOURCES : String[]
        {static} - MODERN_RESOURCES : String[]
        + UltimaMenu()
        + getFamily()
        + getModel()
        + getStyle()
        + getStyleClass()
        + getWidgetVar()
        + processEvent()
        + resolveWidgetVar()
        + setModel()
        + setStyle()
        + setStyleClass()
        + setWidgetVar()
    }
  }
  

  namespace org.primefaces.ultima.component.menu {
    enum PropertyKeys {
      model
      style
      styleClass
      widgetVar
      toString
    }
  }
  

  namespace org.primefaces.ultima.component.menu {
    class org.primefaces.ultima.component.menu.UltimaMenuRenderer {
        # encodeElement()
        # encodeElements()
        # encodeItemIcon()
        # encodeMarkup()
        # encodeMenuItem()
        # encodeMenuItemContent()
        # encodeScript()
        # encodeSeparator()
        # encodeSubmenu()
        # encodeToggleIcon()
    }
  }
  

  org.primefaces.ultima.component.menu.UltimaMenu .up.|> javax.faces.event.ComponentSystemEventListener
  org.primefaces.ultima.component.menu.UltimaMenu .up.|> org.primefaces.component.api.Widget
  org.primefaces.ultima.component.menu.UltimaMenu -up-|> org.primefaces.component.menu.AbstractMenu
  org.primefaces.ultima.component.menu.UltimaMenu +-down- org.primefaces.ultima.component.menu.UltimaMenu.PropertyKeys
  org.primefaces.ultima.component.menu.UltimaMenuRenderer -up-|> org.primefaces.component.menu.BaseMenuRenderer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
