@startuml

title __GESTIONEPERMESSI's Class Diagram__\n

  namespace com.woonders.lacemsjsf.view.gestionepermessi {
    class com.woonders.lacemsjsf.view.gestionepermessi.GestionePermessiView {
        {static} + JSF_NAME : String
        {static} + NAME : String
        - aziendaCount : long
        - operatorViewModelLazyDataModelList : LazyDataModel<OperatorViewModel>
        - roleViewModelList : List<RoleViewModel>
        - simulatorEnabled : boolean
        + calcNotPermissionValue()
        + getAziendaCount()
        + getAziendaSelectionView()
        + getAziendaService()
        + getGestionePermessiService()
        + getHttpSessionUtil()
        + getOperatorService()
        + getOperatorToAssignProfile()
        + getOperatorViewModelLazyDataModelList()
        + getPermission()
        + getPermissionProfile()
        + getProfilePermissionFromOperator()
        + getRoleService()
        + getRoleViewModelList()
        + getSettingService()
        + hasGestionePermessiRole()
        + init()
        + isSimulatorEnabled()
        + permissionChangedEvent()
        + saveOperatorPermission()
        + setAziendaCount()
        + setAziendaSelectionView()
        + setAziendaService()
        + setGestionePermessiService()
        + setHttpSessionUtil()
        + setOperatorService()
        + setOperatorToAssignProfile()
        + setOperatorToAssignProfileFromDatalist()
        + setOperatorViewModelLazyDataModelList()
        + setPermissionProfile()
        + setProfilePermission()
        + setRoleService()
        + setRoleViewModelList()
        + setSettingService()
        + setSimulatorEnabled()
    }
  }
  

  com.woonders.lacemsjsf.view.gestionepermessi.GestionePermessiView o-- com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView : aziendaSelectionView
  com.woonders.lacemsjsf.view.gestionepermessi.GestionePermessiView o-- com.woonders.lacemscommon.service.AziendaService : aziendaService
  com.woonders.lacemsjsf.view.gestionepermessi.GestionePermessiView o-- com.woonders.lacemscommon.service.GestionePermessiService : gestionePermessiService
  com.woonders.lacemsjsf.view.gestionepermessi.GestionePermessiView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.gestionepermessi.GestionePermessiView o-- com.woonders.lacemscommon.service.OperatorService : operatorService
  com.woonders.lacemsjsf.view.gestionepermessi.GestionePermessiView o-- com.woonders.lacemscommon.app.viewmodel.OperatorViewModel : operatorToAssignProfile
  com.woonders.lacemsjsf.view.gestionepermessi.GestionePermessiView o-- com.woonders.lacemscommon.laceenum.PermissionProfile : permissionProfile
  com.woonders.lacemsjsf.view.gestionepermessi.GestionePermessiView o-- com.woonders.lacemscommon.service.RoleService : roleService
  com.woonders.lacemsjsf.view.gestionepermessi.GestionePermessiView o-- com.woonders.lacemscommon.service.SettingService : settingService


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
