@startuml

title __PRESTITI's Class Diagram__\n

  namespace com.woonders.lacemsjsf.view.prestiti {
    class com.woonders.lacemsjsf.view.prestiti.CessioniRendered {
        + isCapPrecedente()
        + isCivicoPrecedente()
        + isComponentiFamiliari()
        + isCoobbligatoPanel()
        + isCtr()
        + isDataIstruita()
        + isDataResidenza()
        + isDataRinnovo()
        + isGaranzia()
        + isIndirizzoPrecedente()
        + isInteressi()
        + isLuogoPrecedente()
        + isModuliPanel()
        + isMontante()
        + isMutuo()
        + isNazionePrecedente()
        + isNetto()
        + isNettoRicavo()
        + isProvinciaPrecedente()
        + isQuinto()
        + isSecci()
        + isSpese()
        + isSpeseAbitazione()
        + isStatoCivile()
        + isStatoPatrimoniale()
        + isTelLavoro()
        + isTipoAbitazione()
        + isTipoContratto()
        + isTipoPraticaDisabled()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.prestiti {
    interface com.woonders.lacemsjsf.view.prestiti.PraticaRendered {
        {abstract} + isCapPrecedente()
        {abstract} + isCivicoPrecedente()
        {abstract} + isComponentiFamiliari()
        {abstract} + isCoobbligatoPanel()
        {abstract} + isCtr()
        {abstract} + isDataIstruita()
        {abstract} + isDataResidenza()
        {abstract} + isDataRinnovo()
        {abstract} + isGaranzia()
        {abstract} + isIndirizzoPrecedente()
        {abstract} + isInteressi()
        {abstract} + isLuogoPrecedente()
        {abstract} + isModuliPanel()
        {abstract} + isMontante()
        {abstract} + isMutuo()
        {abstract} + isNazionePrecedente()
        {abstract} + isNetto()
        {abstract} + isNettoRicavo()
        {abstract} + isProvinciaPrecedente()
        {abstract} + isQuinto()
        {abstract} + isSecci()
        {abstract} + isSpese()
        {abstract} + isSpeseAbitazione()
        {abstract} + isStatoCivile()
        {abstract} + isStatoPatrimoniale()
        {abstract} + isTelLavoro()
        {abstract} + isTipoAbitazione()
        {abstract} + isTipoContratto()
        {abstract} + isTipoPraticaDisabled()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.prestiti {
    class com.woonders.lacemsjsf.view.prestiti.PrestitiRendered {
        + isCapPrecedente()
        + isCivicoPrecedente()
        + isComponentiFamiliari()
        + isCoobbligatoPanel()
        + isCtr()
        + isDataIstruita()
        + isDataResidenza()
        + isDataRinnovo()
        + isGaranzia()
        + isIndirizzoPrecedente()
        + isInteressi()
        + isLuogoPrecedente()
        + isModuliPanel()
        + isMontante()
        + isMutuo()
        + isNazionePrecedente()
        + isNetto()
        + isNettoRicavo()
        + isProvinciaPrecedente()
        + isQuinto()
        + isSecci()
        + isSpese()
        + isSpeseAbitazione()
        + isStatoCivile()
        + isStatoPatrimoniale()
        + isTelLavoro()
        + isTipoAbitazione()
        + isTipoContratto()
        + isTipoPraticaDisabled()
    }
  }
  

  com.woonders.lacemsjsf.view.prestiti.CessioniRendered .up.|> com.woonders.lacemsjsf.view.prestiti.PraticaRendered
  com.woonders.lacemsjsf.view.prestiti.PrestitiRendered .up.|> com.woonders.lacemsjsf.view.prestiti.PraticaRendered


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
