@startuml

title __ANTIRICICLAGGIO's Class Diagram__\n

  namespace com.woonders.lacemsjsf.view.antiriciclaggio {
    class com.woonders.lacemsjsf.view.antiriciclaggio.AntiRiciclaggioView {
        - cf : String
        - dataCarEnd : Date
        - dataCarStart : Date
        + getCf()
        + getDataCarEnd()
        + getDataCarStart()
        + getHttpSessionUtil()
        + getPassaggioParametriUtils()
        + searchByCf()
        + searchDataCaricamentoNonIstruita()
        + setCf()
        + setDataCarEnd()
        + setDataCarStart()
        + setHttpSessionUtil()
        + setPassaggioParametriUtils()
        - searchAntiriciclaggio()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.antiriciclaggio {
    class com.woonders.lacemsjsf.view.antiriciclaggio.DatatableAntiriciclaggioView {
        - clientePraticaLazyDataModel : LazyDataModel<ClientePratica>
        + getAntiriciclaggioService()
        + getAziendaSelectionView()
        + getClientePraticaLazyDataModel()
        + getFileService()
        + getHttpSessionUtil()
        + getPassaggioParametriUtils()
        + getPropertiesUtil()
        + getRequestTenantIdentifierResolver()
        + init()
        + preProcessPDF()
        + setAntiriciclaggioService()
        + setAziendaSelectionView()
        + setClientePraticaLazyDataModel()
        + setFileService()
        + setHttpSessionUtil()
        + setPassaggioParametriUtils()
        + setPropertiesUtil()
        + setRequestTenantIdentifierResolver()
        + showAntiriciclaggioPdf()
    }
  }
  

  com.woonders.lacemsjsf.view.antiriciclaggio.AntiRiciclaggioView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.antiriciclaggio.AntiRiciclaggioView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.antiriciclaggio.AntiRiciclaggioView o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.antiriciclaggio.DatatableAntiriciclaggioView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.antiriciclaggio.DatatableAntiriciclaggioView o-- com.woonders.lacemscommon.service.AntiriciclaggioService : antiriciclaggioService
  com.woonders.lacemsjsf.view.antiriciclaggio.DatatableAntiriciclaggioView o-- com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView : aziendaSelectionView
  com.woonders.lacemsjsf.view.antiriciclaggio.DatatableAntiriciclaggioView o-- com.woonders.lacemscommon.service.FileService : fileService
  com.woonders.lacemsjsf.view.antiriciclaggio.DatatableAntiriciclaggioView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.antiriciclaggio.DatatableAntiriciclaggioView o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.antiriciclaggio.DatatableAntiriciclaggioView o-- com.woonders.lacemsjsf.config.PropertiesUtil : propertiesUtil
  com.woonders.lacemsjsf.view.antiriciclaggio.DatatableAntiriciclaggioView o-- com.woonders.lacemsjsf.db.app.config.RequestTenantIdentifierResolver : requestTenantIdentifierResolver


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
