@startuml

title __DB's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace db {
      class com.woonders.lacemscommon.db.QueryDSLHelper {
          + createFilterPredicate()
          + createSortOrder()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      enum SortOrder {
        ASCENDING
        DESCENDING
        UNSORTED
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      enum TableField {
        COGNOME
        COGNOME_CLIENTE_VIEW_MODEL
        DATA_CARICAMENTO
        DATA_CARICAMENTO_PRATICA_VIEW_MODEL
        DATA_CREAZIONE_PREVENTIVO
        DATA_DECORRENZA
        DATA_DELIBERA
        DATA_DI_NASCITA
        DATA_DI_NASCITA_CLIENTE_VIEW_MODEL
        DATA_FIRMA_CONTRATTI
        DATA_INSERIMENTO_CLIENTE
        DATA_INSERIMENTO_CLIENTE_VIEW_MODEL
        DATA_ISTRUITA
        DATA_ISTRUTTORIA
        DATA_LIQUIDAZIONE
        DATA_PERFEZIONAMENTO
        DATA_RECALL_NOMINATIVO
        DATA_RECALL_PRATICA_VIEW_MODEL
        DATA_RINNOVO_PRATICA_VIEW_MODEL
        DATA_RINNOVO_TRATTENUTA
        DATA_RINNOVO_TRATTENUTA_VIEW_MODEL
        DATE_TIME_CREATION_NOTICE_BOARD
        DESCRIZIONE_PROVENIENZA
        DURATA
        DURATA_ESTINZIONE
        DURATA_PRATICA_VIEW_MODEL
        DURATA_PREVENTIVO
        DURATA_TRATTENUTA
        DURATA_TRATTENUTA_VIEW_MODEL
        FORNITORE_LEAD
        IMPIEGO
        IMPORTO_EROGATO
        IMPORTO_EROGATO_PRATICA_VIEW_MODEL
        IMPORTO_EROGATO_PREVENTIVO
        ISTITUTO
        LOG_EXECUTION_DATE_TIME
        NOTIFICA_ESTINZIONE
        NOTIFICA_STATO_PRATICA
        OPERATORE
        OPERATORE_NOMINATIVO
        OPERATORE_NOMINATIVO_CLIENTE_VIEW_MODEL
        OPERATORE_PRATICA_VIEW_MODEL
        PROVENIENZA
        PROVINCIA_RESIDENZA
        PROVINCIA_RESIDENZA_RESIDENZA_VIEW_MODEL
        RATA
        RATA_ESTINZIONE
        RATA_PRATICA_VIEW_MODEL
        RATA_PREVENTIVO
        RATA_TRATTENUTA
        RATA_TRATTENUTA_VIEW_MODEL
        RICARICA_DATE_TIME
        RINNOVO_ESTINZIONE
        SCADENZA_TRATTENUTA
        SCADENZA_TRATTENUTA_VIEW_MODEL
        SIMULATOR_JOB_TYPE_LIST
        SIMULATOR_TABLE_STATUS
        SIMULATOR_TABLE_TYPE
        STATO_NOMINATIVO
        STATO_NOMINATIVO_CLIENTE_VIEW_MODEL
        TIPOLOGIA_PREVENTIVO
        TIPO_ESTINZIONE
        TIPO_OPERAZIONE_PREVENTIVO
        TIPO_PRATICA
        TIPO_PRATICA_PRATICA_VIEW_MODEL
        TIPO_TRATTENUTA
        TIPO_TRATTENUTA_VIEW_MODEL
        value
      }
    }
  }
  

  com.woonders.lacemscommon.db.QueryDSLHelper +-down- com.woonders.lacemscommon.db.QueryDSLHelper.SortOrder
  com.woonders.lacemscommon.db.QueryDSLHelper +-down- com.woonders.lacemscommon.db.QueryDSLHelper.TableField


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
