@startuml

title __DELETECLIENTEPRATICA's Class Diagram__\n

  namespace com.woonders.lacemsjsf.view.deleteclientepratica {
    class com.woonders.lacemsjsf.view.deleteclientepratica.DatatableDeletePraticaView {
        {static} + JSF_NAME : String
        {static} + NAME : String
        - clientiList : List<ClientePratica>
        {static} - logger : Logger
        + confirmDelete()
        + getClientiList()
        + getDeleteClienteService()
        + getPassaggioParametriUtils()
        + getPropertiesUtil()
        + getRequestTenantIdentifierResolver()
        + getSelectedPratica()
        + init()
        + onRowSelect()
        + setClientiList()
        + setDeleteClienteService()
        + setPassaggioParametriUtils()
        + setPropertiesUtil()
        + setRequestTenantIdentifierResolver()
        + setSelectedPratica()
        - retrieveListPraticheToDeleteFromParameter()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.deleteclientepratica {
    class com.woonders.lacemsjsf.view.deleteclientepratica.DeleteView {
        {static} + JSF_NAME : String
        {static} + NAME : String
        - cfDelete : String
        - cfPraticaDelete : String
        {static} - logger : Logger
        + deleteRecordByCf()
        + getCfDelete()
        + getCfPraticaDelete()
        + getDeleteClienteService()
        + getHttpSessionUtil()
        + getPassaggioParametriUtils()
        + getPropertiesUtil()
        + getRequestTenantIdentifierResolver()
        + isDeleteAllClienteByCfRendered()
        + searchCfDelete()
        + setCfDelete()
        + setCfPraticaDelete()
        + setDeleteClienteService()
        + setHttpSessionUtil()
        + setPassaggioParametriUtils()
        + setPropertiesUtil()
        + setRequestTenantIdentifierResolver()
    }
  }
  

  com.woonders.lacemsjsf.view.deleteclientepratica.DatatableDeletePraticaView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.deleteclientepratica.DatatableDeletePraticaView o-- com.woonders.lacemscommon.service.DeleteClienteService : deleteClienteService
  com.woonders.lacemsjsf.view.deleteclientepratica.DatatableDeletePraticaView o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.deleteclientepratica.DatatableDeletePraticaView o-- com.woonders.lacemsjsf.config.PropertiesUtil : propertiesUtil
  com.woonders.lacemsjsf.view.deleteclientepratica.DatatableDeletePraticaView o-- com.woonders.lacemsjsf.db.app.config.RequestTenantIdentifierResolver : requestTenantIdentifierResolver
  com.woonders.lacemsjsf.view.deleteclientepratica.DatatableDeletePraticaView o-- com.woonders.lacemscommon.app.model.ClientePratica : selectedPratica
  com.woonders.lacemsjsf.view.deleteclientepratica.DeleteView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.deleteclientepratica.DeleteView o-- com.woonders.lacemscommon.service.DeleteClienteService : deleteClienteService
  com.woonders.lacemsjsf.view.deleteclientepratica.DeleteView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.deleteclientepratica.DeleteView o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.deleteclientepratica.DeleteView o-- com.woonders.lacemsjsf.config.PropertiesUtil : propertiesUtil
  com.woonders.lacemsjsf.view.deleteclientepratica.DeleteView o-- com.woonders.lacemsjsf.db.app.config.RequestTenantIdentifierResolver : requestTenantIdentifierResolver


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
