@startuml

title __UTIL's Class Diagram__\n

  namespace com.woonders.lacemsjsf.view.util {
    class com.woonders.lacemsjsf.view.util.ConstantResolverView {
'        {static} + JSF_NAME : String
'        {static} + NAME : String
'        {static} + PDF_SIZE_LIMIT : long
'        - CUSTOMERLY_ENABLED : boolean
'        {static} - MAX_CAT_PENSIONE_LENGTH : int
'        - STRIPE_PUBLISHABLE_KEY : String
'        - allowTypesFile : String
'        - allowTypesImportFileCampagne : String
'        - amministrazioneListMaxSize : Integer
'        - amministrazioneListNominativoMaxSize : Integer
'        - calendarMinHour : Integer
'        - cancelLabelButtonFile : String
'        - cessionePensione : String
'        - cessioneStipendio : String
'        - chooseLabelButtonFile : String
'        - delega : String
'        - excelCampagneSizeLimit : long
'        - impegniEstinguibiliMaxSize : Integer
'        - importLabelButtonFile : String
'        - istitutoList : List<String>
'        {static} - maxAnniAssunzioneCampagnaRange : Integer
'        - maxEtaCampagnaRange : Integer
'        - maxFileImportCampagne : Integer
'        - maxLengthCommentoLog : int
'        - maxLengthTelephone : Integer
'        {static} - minAnniAssunzioneCampagnaRange : Integer
'        - minEtaCampagnaRange : Integer
'        - minLengthLastname : Integer
'        - minLengthTelephone : Integer
'        - minValueOfSpinnerGiorniNotifica : Integer
'        - prestito : String
'        - preventivoListMaxSize : Integer
'        - uploadLabelButtonFile : String
'        - valutazioneListMaxSize : Integer
        + getAllStatoPratica()
        + getAllowTypesFile()
        + getAllowTypesImportFileCampagne()
        + getAmministrazioneListMaxSize()
        + getAmministrazioneListNominativoMaxSize()
        + getAnalyticsDates()
        + getCalendarMinHour()
        + getCancelLabelButtonFile()
        + getCessionePensione()
        + getCessioneStipendio()
        + getChooseLabelButtonFile()
        + getCompagnie()
        + getDelega()
        + getDurataPratica()
        + getEsitoSmsNotificaLead()
        + getExcelCampagneSizeLimit()
        + getFeeType()
        + getFiltroRinnoviPraticaCoesistenza()
        + getFornitoreLead()
        + getGraficoEnum()
        + getImpegniEstinguibiliMaxSize()
        + getImpieghiListString()
        + getImpiego()
        + getImportLabelButtonFile()
        + getIstitutoList()
        + getListAnniAssunzioneNuovaCampagna()
        + getMaxCatPensioneLength()
        + getMaxEtaCampagnaRange()
        + getMaxFileImportCampagne()
        + getMaxLengthCommentoLog()
        + getMaxLengthTelephone()
        + getMensilita()
        + getMenuSection()
        + getMinEtaCampagnaRange()
        + getMinLengthLastname()
        + getMinLengthTelephone()
        + getMinValueOfSpinnerGiorniNotifica()
        + getPdfSizeLimit()
        + getPermissionProfile()
        + getPermissionType()
        + getPrestito()
        + getPreventivoListMaxSize()
        + getProvenienza()
        + getRicaricaType()
        + getSesso()
        + getSimulatorDisclaimerMessage()
        + getSimulatorRoundingMode()
        + getSimulatorTableStatus()
        + getSpeseList()
        + getStatoConteggioEstinzione()
        + getStatoNominativo()
        + getStatoNominativoFromString()
        + getStatoPraticaByTipo()
        + getStatoPraticaFiltroCampagne()
        + getStripePublishableKey()
        + getTipo()
        + getTipoDocumento()
        + getTipoImpegno()
        + getTipoPratica()
        + getTipoPraticaCessioneValue()
        + getTipoPraticaPrestitoValue()
        + getTipoRinnovo()
        + getTipologiaPreventivo()
        + getUploadLabelButtonFile()
        + getValutazioneListMaxSize()
        + getValutazioni()
        + init()
        + isCustomerlyEnabled()
        + setAziendaService()
        + setIstitutoList()
        + setPropertiesUtil()
        + tipoArticoloFromString()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.util {
    class com.woonders.lacemsjsf.view.util.UtilResolverView {
        {static} + JSF_NAME : String
        {static} + NAME : String
        + getAllOperatorsForSearch()
        + getAziendaSelectionView()
        + getDateConversionUtil()
        + getHttpSessionUtil()
        + getNewDate()
        + getOperatorService()
        + getOperatorsList()
        + getOperatorsStringList()
        + isCampagneMarketingMenuEntryRendered()
        + isRenderedColumn()
        + minDateCalendarFromLocalDateTime()
        + minHourCalendarFromLocalDateTime()
        + minMinuteCalendarFromLocalDateTime()
        + setAziendaSelectionView()
        + setDateConversionUtil()
        + setHttpSessionUtil()
        + setOperatorService()
        - generateOperatorUsernameList()
    }
  }
  

  com.woonders.lacemsjsf.view.util.ConstantResolverView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.util.ConstantResolverView o-- com.woonders.lacemscommon.service.AziendaService : aziendaService
  com.woonders.lacemsjsf.view.util.ConstantResolverView o-- com.woonders.lacemsjsf.config.PropertiesUtil : propertiesUtil
  com.woonders.lacemsjsf.view.util.UtilResolverView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.util.UtilResolverView o-- com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView : aziendaSelectionView
  com.woonders.lacemsjsf.view.util.UtilResolverView o-- com.woonders.lacemscommon.util.DateConversionUtil : dateConversionUtil
  com.woonders.lacemsjsf.view.util.UtilResolverView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.util.UtilResolverView o-- com.woonders.lacemscommon.service.OperatorService : operatorService


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
