@startuml

title __CONVERTER's Class Diagram__\n

  namespace com.woonders.lacemsapi.converter {
    class com.woonders.lacemsapi.converter.ClienteImpiegoConverter {
        - clientJobTypeStringList : List<String>
        - clienteImpiegoStringList : List<String>
        {static} - log : Logger
        + ClienteImpiegoConverter()
        + convert()
        - fromDevisProx()
        - fromOurWebsites()
    }
  }
  

  namespace com.woonders.lacemsapi.converter {
    class com.woonders.lacemsapi.converter.LocalDateConverter {
        - dateTimeFormatter : DateTimeFormatter
        {static} - logger : Logger
        + convert()
        + deserialize()
        - parseDate()
    }
  }
  

  namespace com.woonders.lacemsapi.converter {
    class com.woonders.lacemsapi.converter.MessageTypeConverter {
        {static} - log : Logger
        + convert()
    }
  }
  

  namespace com.woonders.lacemsapi.converter {
    class com.woonders.lacemsapi.converter.ProvenienzaConverter {
        {static} - log : Logger
        + convert()
        + deserialize()
        - parseProvenienza()
    }
  }
  

  namespace com.woonders.lacemsapi.converter {
    class com.woonders.lacemsapi.converter.StringToBigDecimalConverter {
        {static} - logger : Logger
        + convert()
    }
  }
  

  namespace com.woonders.lacemsapi.converter {
    class com.woonders.lacemsapi.converter.StringToIntConverter {
        {static} - logger : Logger
        + convert()
    }
  }
  

  com.woonders.lacemsapi.converter.ClienteImpiegoConverter .up.|> org.springframework.core.convert.converter.Converter
  com.woonders.lacemsapi.converter.LocalDateConverter .up.|> org.springframework.core.convert.converter.Converter
  com.woonders.lacemsapi.converter.LocalDateConverter -up-|> com.fasterxml.jackson.databind.JsonDeserializer
  com.woonders.lacemsapi.converter.MessageTypeConverter .up.|> org.springframework.core.convert.converter.Converter
  com.woonders.lacemsapi.converter.ProvenienzaConverter .up.|> org.springframework.core.convert.converter.Converter
  com.woonders.lacemsapi.converter.ProvenienzaConverter -up-|> com.fasterxml.jackson.databind.JsonDeserializer
  com.woonders.lacemsapi.converter.StringToBigDecimalConverter .up.|> org.springframework.core.convert.converter.Converter
  com.woonders.lacemsapi.converter.StringToIntConverter .up.|> org.springframework.core.convert.converter.Converter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
