@startuml

title __LACEENUM's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace laceenum {
      enum AnalyticsDateEnum {
        CURRENT_MONTH
        CURRENT_YEAR
        LAST_30
        LAST_60
        LAST_90
        LAST_YEAR
        value
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace laceenum {
      enum FiltroRinnoviPraticaCoesistenza {
        ALL_RINNOVI
        RINNOVI_COESISTENZA
        RINNOVI_PRATICA
        value
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace laceenum {
      enum GraficoEnum {
        EROGATO
        MONTANTE
        MONTANTE_PERFEZIONATO
        value
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace laceenum {
      enum PermissionProfile {
        COLLABORATORE
        DIPENDENTE_AVANZATO
        DIPENDENTE_AVANZATO_MULTIAGENZIA
        DIPENDENTE_BASE
        UTENTE_DISABILITATO
        value
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace laceenum {
      enum SimulatorSource {
        NOMINATIVO
        PREVENTIVO_CLIENTE
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace laceenum {
      enum StringCalc {
        DATA
        EURO
        PERC
        RATE
        value
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace laceenum {
      enum TipoRinnovo {
        COESISTENZA
        PRATICA
        value
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
