@startuml

title __SEARCH's Class Diagram__\n

  namespace com.woonders.lacemsjsf.view.search {
    class com.woonders.lacemsjsf.view.search.ClientiNominativiConverter {
        + ClientiNominativiConverter()
        + getAsObject()
        + getAsString()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.search {
    class com.woonders.lacemsjsf.view.search.DatatableAdvancedSearchClientiView {
        {static} + JSF_NAME : String
        {static} + NAME : String
        - clientePraticaLazyDataModel : LazyDataModel<ClientePratica>
        + getAdvancedSearchClientiViewModel()
        + getAziendaSelectionView()
        + getClientePraticaLazyDataModel()
        + getHttpSessionUtil()
        + getPassaggioParametriUtils()
        + getSearchService()
        + getSelectedCliente()
        + init()
        + isRenderedColumnCoesistenza()
        + onRowSelect()
        + setAdvancedSearchClientiViewModel()
        + setAziendaSelectionView()
        + setClientePraticaLazyDataModel()
        + setHttpSessionUtil()
        + setPassaggioParametriUtils()
        + setSearchService()
        + setSelectedCliente()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.search {
    class com.woonders.lacemsjsf.view.search.DatatableAdvancedSearchNominativiView {
        {static} + JSF_NAME : String
        {static} + NAME : String
        - clienteViewModelLazyDataModel : LazyDataModel<ClienteViewModel>
        + getAdvancedSearchNominativiViewModel()
        + getAziendaSelectionView()
        + getClienteViewModelLazyDataModel()
        + getHttpSessionUtil()
        + getPassaggioParametriUtils()
        + getSearchService()
        + getSelectedNominativo()
        + init()
        + onRowSelect()
        + setAdvancedSearchNominativiViewModel()
        + setAziendaSelectionView()
        + setClienteViewModelLazyDataModel()
        + setHttpSessionUtil()
        + setPassaggioParametriUtils()
        + setSearchService()
        + setSelectedNominativo()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.search {
    class com.woonders.lacemsjsf.view.search.DatatableSearchView {
        {static} + JSF_NAME : String
        {static} + NAME : String
        - clientiList : List<ClientePratica>
        + getCheckPermissionUtils()
        + getClientiList()
        + getHttpSessionUtil()
        + getPassaggioParametriUtils()
        + getPropertiesUtil()
        + getRowKey()
        + getSearchService()
        + getSelectedClienteNominativo()
        + init()
        + onRowSelect()
        + setCheckPermissionUtils()
        + setClientiList()
        + setHttpSessionUtil()
        + setPassaggioParametriUtils()
        + setPropertiesUtil()
        + setSearchService()
        + setSelectedClienteNominativo()
        + valueOfInsertionDate()
        + valueOfOperator()
        + valueOfTypeOperation()
        - retrieveClienteDaCheckNominativoFromParameter()
        - retrieveClienteNominativoListFromParameter()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.search {
    class com.woonders.lacemsjsf.view.search.Search {
        {static} + JSF_NAME : String
        {static} + NAME : String
        - cfSearch : String
        - clientiList : List<ClientePratica>
        - cognomeSearch : String
        - nrContratto : String
        - nrSecci : String
        - telefono : String
        + advancedSearchCliente()
        + advancedSearchNominativo()
        + completeAmministrazione()
        + getAdvancedSearchClienti()
        + getAdvancedSearchNominativi()
        + getAdvancedSearchUtil()
        + getAmministrazioneService()
        + getCfSearch()
        + getClientiList()
        + getCognomeSearch()
        + getHttpSessionUtil()
        + getNrContratto()
        + getNrSecci()
        + getOperatorListClienti()
        + getOperatorListNominativi()
        + getOperatorService()
        + getPassaggioParametriUtils()
        + getPropertiesUtil()
        + getSearchService()
        + getTelefono()
        + init()
        + isAziendaRenderedCliente()
        + isAziendaRenderedNominativo()
        + isDisabledAnniAssunzionePensionamento()
        + isDisabledDateRinnovi()
        + isRenderedSelectItemsOperatorsCliente()
        + isRenderedSelectItemsOperatorsNominativo()
        + isRicercaAvanzataClienteRendered()
        + isRicercaAvanzataNominativoRendered()
        + searchByNrContratto()
        + searchCF()
        + searchCognome()
        + searchTelefono()
        + setAdvancedSearchClienti()
        + setAdvancedSearchNominativi()
        + setAdvancedSearchUtil()
        + setAmministrazioneService()
        + setCfSearch()
        + setClientiList()
        + setCognomeSearch()
        + setHttpSessionUtil()
        + setNrContratto()
        + setNrSecci()
        + setOperatorService()
        + setPassaggioParametriUtils()
        + setPropertiesUtil()
        + setSearchService()
        + setTelefono()
    }
  }
  

  com.woonders.lacemsjsf.view.search.ClientiNominativiConverter -up-|> com.woonders.lacemsjsf.util.BaseConverter
  com.woonders.lacemsjsf.view.search.ClientiNominativiConverter o-- com.woonders.lacemscommon.service.SearchService : searchService
  com.woonders.lacemsjsf.view.search.DatatableAdvancedSearchClientiView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.search.DatatableAdvancedSearchClientiView o-- com.woonders.lacemscommon.app.model.AdvancedSearchViewModel : advancedSearchClientiViewModel
  com.woonders.lacemsjsf.view.search.DatatableAdvancedSearchClientiView o-- com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView : aziendaSelectionView
  com.woonders.lacemsjsf.view.search.DatatableAdvancedSearchClientiView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.search.DatatableAdvancedSearchClientiView o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.search.DatatableAdvancedSearchClientiView o-- com.woonders.lacemscommon.service.SearchService : searchService
  com.woonders.lacemsjsf.view.search.DatatableAdvancedSearchClientiView o-- com.woonders.lacemscommon.app.model.ClientePratica : selectedCliente
  com.woonders.lacemsjsf.view.search.DatatableAdvancedSearchNominativiView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.search.DatatableAdvancedSearchNominativiView o-- com.woonders.lacemscommon.app.model.AdvancedSearchViewModel : advancedSearchNominativiViewModel
  com.woonders.lacemsjsf.view.search.DatatableAdvancedSearchNominativiView o-- com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView : aziendaSelectionView
  com.woonders.lacemsjsf.view.search.DatatableAdvancedSearchNominativiView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.search.DatatableAdvancedSearchNominativiView o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.search.DatatableAdvancedSearchNominativiView o-- com.woonders.lacemscommon.service.SearchService : searchService
  com.woonders.lacemsjsf.view.search.DatatableAdvancedSearchNominativiView o-- com.woonders.lacemscommon.app.viewmodel.ClienteViewModel : selectedNominativo
  com.woonders.lacemsjsf.view.search.DatatableSearchView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.search.DatatableSearchView o-- com.woonders.lacemscommon.service.SearchService : searchService
  com.woonders.lacemsjsf.view.search.DatatableSearchView o-- com.woonders.lacemsjsf.util.CheckPermissionUtils : checkPermissionUtils
  com.woonders.lacemsjsf.view.search.DatatableSearchView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.search.DatatableSearchView o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.search.DatatableSearchView o-- com.woonders.lacemsjsf.config.PropertiesUtil : propertiesUtil
  com.woonders.lacemsjsf.view.search.DatatableSearchView o-- com.woonders.lacemscommon.app.model.ClientePratica : selectedClienteNominativo
  com.woonders.lacemsjsf.view.search.Search .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.search.Search o-- com.woonders.lacemscommon.app.model.AdvancedSearchViewModel : advancedSearchClienti
  com.woonders.lacemsjsf.view.search.Search o-- com.woonders.lacemscommon.app.model.AdvancedSearchViewModel : advancedSearchNominativi
  com.woonders.lacemsjsf.view.search.Search o-- com.woonders.lacemscommon.util.AdvancedSearchUtil : advancedSearchUtil
  com.woonders.lacemsjsf.view.search.Search o-- com.woonders.lacemscommon.service.AmministrazioneService : amministrazioneService
  com.woonders.lacemsjsf.view.search.Search o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.search.Search o-- com.woonders.lacemscommon.service.OperatorService : operatorService
  com.woonders.lacemsjsf.view.search.Search o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.search.Search o-- com.woonders.lacemsjsf.config.PropertiesUtil : propertiesUtil
  com.woonders.lacemsjsf.view.search.Search o-- com.woonders.lacemscommon.service.SearchService : searchService


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
