@startuml

title __UTIL's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace app.model {
      namespace util {
        class com.woonders.lacemscommon.app.model.util.ClientePraticaUtil {
            + generateClientePraticaList()
            + generateClientePraticaList()
            + generateClientePreventivoList()
            + generateClientePreventivoList()
            + generateClienteTrattenuteViewModel()
            + generateEstinzionePraticaListFromEstinzioneList()
            + generateEstinzionePraticaListFromEstinzioneList()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      namespace util {
        class com.woonders.lacemscommon.app.model.util.PraticheInCorsoModelUtil {
            + createModel()
        }
      }
    }
  }
  

  com.woonders.lacemscommon.app.model.util.ClientePraticaUtil o-- com.woonders.lacemscommon.app.viewmodel.creator.ClienteViewModelCreator : clienteViewModelCreator
  com.woonders.lacemscommon.app.model.util.ClientePraticaUtil o-- com.woonders.lacemscommon.app.viewmodel.creator.EstinzioneViewModelCreator : estinzioneViewModelCreator
  com.woonders.lacemscommon.app.model.util.ClientePraticaUtil o-- com.woonders.lacemscommon.app.viewmodel.creator.PraticaViewModelCreator : praticaViewModelCreator
  com.woonders.lacemscommon.app.model.util.ClientePraticaUtil o-- com.woonders.lacemscommon.app.viewmodel.creator.PreventivoViewModelCreator : preventivoViewModelCreator
  com.woonders.lacemscommon.app.model.util.ClientePraticaUtil o-- com.woonders.lacemscommon.app.viewmodel.creator.TrattenuteViewModelCreator : trattenuteViewModelCreator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
