@startuml

title __PDF's Class Diagram__\n

  namespace com.woonders.lacemsjsf.view.pdf {
    class com.woonders.lacemsjsf.view.pdf.AllegatiPdf {
        {static} + JSF_NAME : String
        {static} + NAME : String
        + getConstantResolverView()
        + riempiAllegatiPDF()
        + setConstantResolverView()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.pdf {
    class com.woonders.lacemsjsf.view.pdf.AmministrazionePdf {
        {static} + JSF_NAME : String
        {static} + NAME : String
        + riempiAmministration()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.pdf {
    class com.woonders.lacemsjsf.view.pdf.AnagraficaPdf {
        {static} + JSF_NAME : String
        {static} + NAME : String
        + riempiAnagraficaPDF()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.pdf {
    abstract class com.woonders.lacemsjsf.view.pdf.BasePdfComponent {
        {static} - BASE_PDF_PATH : String
        - amazonS3 : AmazonS3
        {static} - log : Logger
        + loadPDDocumentFromDisk()
        - addCurrentFinanziaria()
        - addCurrentTenant()
        - addFinanziariaPath()
        - addTenantPath()
        - checkIfLocalFileExists()
        - getPdfFileFromS3()
        - loadPdf()
        - readFileFromDisk()
        - writeFileToDisk()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.pdf {
    class com.woonders.lacemsjsf.view.pdf.ControlNull {
        + checkNull()
        + setValueEmpty()
        - getDefaultValueForType()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.pdf {
    enum FinanziariaEnum {
      ITALCREDI
      MEDIOLANUM
      fieldName
    }
  }
  

  namespace com.woonders.lacemsjsf.view.pdf {
    class com.woonders.lacemsjsf.view.pdf.NominativoPdf {
        {static} + JSF_NAME : String
        {static} + NAME : String
        + riempiAllegatiPDF()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.pdf {
    class com.woonders.lacemsjsf.view.pdf.PdfView {
        - file : ByteArrayOutputStream
        {static} - log : Logger
        + PdfView()
        + getFile()
        + getIdFile()
        + getPassaggioParametriUtils()
        + getPdfLink()
        + getStream()
        + isLinkToShow()
        + setFile()
        + setPassaggioParametriUtils()
        + setStream()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.pdf {
    class com.woonders.lacemsjsf.view.pdf.PrefinPdf {
        {static} + JSF_NAME : String
        {static} + NAME : String
        + riempiPreconPDF()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.pdf {
    class com.woonders.lacemsjsf.view.pdf.PrivacyPdf {
        {static} + JSF_NAME : String
        {static} + NAME : String
        + riempiPrivacyPDF()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.pdf {
    class com.woonders.lacemsjsf.view.pdf.SelectPages {
        ~ hashPage : HashMap<PDPage, Integer>
        + addPages()
        - initHashMap()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.pdf {
    class com.woonders.lacemsjsf.view.pdf.SelectionPagesAllegati {
        + setPagesAllegatiItalcredi()
        ~ setPagesAllegatiMediolanum()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.pdf {
    class com.woonders.lacemsjsf.view.pdf.ShowPdfView {
        - fileName : String
        {static} - logger : Logger
        - streamedContent : StreamedContent
        + createStream()
        + getFileName()
        + getIdFile()
        + getStreamedContent()
        + init()
        + setFileService()
        + setPassaggioParametriUtils()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.pdf {
    class com.woonders.lacemsjsf.view.pdf.StreamPdf {
        + getStream()
    }
  }
  

  com.woonders.lacemsjsf.view.pdf.AllegatiPdf -up-|> com.woonders.lacemsjsf.view.pdf.BasePdfComponent
  com.woonders.lacemsjsf.view.pdf.AllegatiPdf o-- com.woonders.lacemsjsf.db.app.model.util.ClienteViewModelUtil : clienteViewModelUtil
  com.woonders.lacemsjsf.view.pdf.AllegatiPdf o-- com.woonders.lacemsjsf.view.util.ConstantResolverView : constantResolverView
  com.woonders.lacemsjsf.view.pdf.AllegatiPdf o-- com.woonders.lacemsjsf.view.pdf.SelectionPagesAllegati : selectionPagesAllegati
  com.woonders.lacemsjsf.view.pdf.AllegatiPdf o-- com.woonders.lacemscommon.app.viewmodel.converter.StringAndBigDecimalConverter : stringAndBigDecimalConverter
  com.woonders.lacemsjsf.view.pdf.AmministrazionePdf -up-|> com.woonders.lacemsjsf.view.pdf.BasePdfComponent
  com.woonders.lacemsjsf.view.pdf.AnagraficaPdf -up-|> com.woonders.lacemsjsf.view.pdf.BasePdfComponent
  com.woonders.lacemsjsf.view.pdf.AnagraficaPdf o-- com.woonders.lacemsjsf.db.app.model.util.ClienteViewModelUtil : clienteViewModelUtil
  com.woonders.lacemsjsf.view.pdf.AnagraficaPdf o-- com.woonders.lacemscommon.app.viewmodel.converter.StringAndBigDecimalConverter : stringAndBigDecimalConverter
  com.woonders.lacemsjsf.view.pdf.BasePdfComponent o-- com.woonders.lacemsjsf.db.app.config.RequestTenantIdentifierResolver : requestTenantIdentifierResolver
  com.woonders.lacemsjsf.view.pdf.NominativoPdf -up-|> com.woonders.lacemsjsf.view.pdf.BasePdfComponent
  com.woonders.lacemsjsf.view.pdf.NominativoPdf o-- com.woonders.lacemscommon.app.viewmodel.converter.StringAndBigDecimalConverter : stringAndBigDecimalConverter
  com.woonders.lacemsjsf.view.pdf.PdfView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.pdf.PdfView o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.pdf.PdfView o-- com.woonders.lacemsjsf.view.pdf.StreamPdf : stream
  com.woonders.lacemsjsf.view.pdf.PrefinPdf -up-|> com.woonders.lacemsjsf.view.pdf.BasePdfComponent
  com.woonders.lacemsjsf.view.pdf.PrefinPdf o-- com.woonders.lacemsjsf.db.app.model.util.ClienteViewModelUtil : clienteViewModelUtil
  com.woonders.lacemsjsf.view.pdf.PrefinPdf o-- com.woonders.lacemscommon.app.viewmodel.converter.StringAndBigDecimalConverter : stringAndBigDecimalConverter
  com.woonders.lacemsjsf.view.pdf.PrivacyPdf -up-|> com.woonders.lacemsjsf.view.pdf.BasePdfComponent
  com.woonders.lacemsjsf.view.pdf.ShowPdfView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.pdf.ShowPdfView o-- com.woonders.lacemscommon.service.FileService : fileService
  com.woonders.lacemsjsf.view.pdf.ShowPdfView o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
