@startuml

title __USERS's Class Diagram__\n

  namespace com.woonders.lacemsjsf.view.sysadmin.users {
    class com.woonders.lacemsjsf.view.sysadmin.users.ManageUsersView {
        + addNewLoginOperatorAction()
        + deleteLoginOperator()
        + getNewOperatorViewModel()
        + getNewRoleViewModel()
        + getOperatorService()
        + getPropertiesUtil()
        + getRoleServiceImpl()
        + getSelectedOperatorViewModel()
        + prepareNewLoginOperatorAction()
        + setNewOperatorViewModel()
        + setNewRoleViewModel()
        + setOperatorService()
        + setPropertiesUtil()
        + setRoleServiceImpl()
        + setSelectedOperatorViewModel()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.sysadmin.users {
    class com.woonders.lacemsjsf.view.sysadmin.users.RoleConverter {
        + RoleConverter()
        + getAsObject()
        + getAsString()
    }
  }
  

  com.woonders.lacemsjsf.view.sysadmin.users.ManageUsersView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.sysadmin.users.ManageUsersView o-- com.woonders.lacemscommon.app.viewmodel.OperatorViewModel : newOperatorViewModel
  com.woonders.lacemsjsf.view.sysadmin.users.ManageUsersView o-- com.woonders.lacemscommon.app.viewmodel.RoleViewModel : newRoleViewModel
  com.woonders.lacemsjsf.view.sysadmin.users.ManageUsersView o-- com.woonders.lacemscommon.service.OperatorService : operatorService
  com.woonders.lacemsjsf.view.sysadmin.users.ManageUsersView o-- com.woonders.lacemsjsf.config.PropertiesUtil : propertiesUtil
  com.woonders.lacemsjsf.view.sysadmin.users.ManageUsersView o-- com.woonders.lacemscommon.service.impl.RoleServiceImpl : roleServiceImpl
  com.woonders.lacemsjsf.view.sysadmin.users.ManageUsersView o-- com.woonders.lacemscommon.app.viewmodel.OperatorViewModel : selectedOperatorViewModel
  com.woonders.lacemsjsf.view.sysadmin.users.RoleConverter -up-|> com.woonders.lacemsjsf.util.BaseConverter
  com.woonders.lacemsjsf.view.sysadmin.users.RoleConverter o-- com.woonders.lacemscommon.service.RoleService : roleService


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
