@startuml

title __ASYNC's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace config {
      namespace async {
        class com.woonders.lacemscommon.config.async.AsyncConfig {
            {static} + SINGLE_TASK_EXECUTOR : String
            + singleTaskExecutor()
            + taskExecutor()
            + threadPoolTaskExecutor()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace config {
      namespace async {
        class com.woonders.lacemscommon.config.async.AsyncConfig.TenantAwareCallable {
            - callable : Callable<T>
            - tenantName : String
            + call()
            - TenantAwareCallable()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace config {
      namespace async {
        class com.woonders.lacemscommon.config.async.AsyncConfig.TenantAwareRunnable {
            - runnable : Runnable
            - tenantName : String
            + TenantAwareRunnable()
            + run()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace config {
      namespace async {
        class com.woonders.lacemscommon.config.async.AsyncConfig.TenantAwareThreadPoolExecutor {
            + submit()
            + submit()
            + submitListenable()
            + submitListenable()
        }
      }
    }
  }
  

  com.woonders.lacemscommon.config.async.AsyncConfig o-- com.woonders.lacemscommon.AsyncTenantStorage : asyncTenantStorage
  com.woonders.lacemscommon.config.async.AsyncConfig o-- com.woonders.lacemscommon.util.RequestUtil : requestUtil
  com.woonders.lacemscommon.config.async.AsyncConfig +-down- com.woonders.lacemscommon.config.async.AsyncConfig.TenantAwareCallable
  com.woonders.lacemscommon.config.async.AsyncConfig +-down- com.woonders.lacemscommon.config.async.AsyncConfig.TenantAwareRunnable
  com.woonders.lacemscommon.config.async.AsyncConfig +-down- com.woonders.lacemscommon.config.async.AsyncConfig.TenantAwareThreadPoolExecutor
  com.woonders.lacemscommon.config.async.AsyncConfig.TenantAwareCallable .up.|> java.util.concurrent.Callable
  com.woonders.lacemscommon.config.async.AsyncConfig.TenantAwareRunnable .up.|> java.lang.Runnable
  com.woonders.lacemscommon.config.async.AsyncConfig.TenantAwareThreadPoolExecutor -up-|> org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
