@startuml

title __CALENDARIOAPPUNTAMENTI's Class Diagram__\n

  namespace com.woonders.lacemsjsf.view.calendarioappuntamenti {
    class com.woonders.lacemsjsf.view.calendarioappuntamenti.CalendarioAppuntamentiView {
        - operatoriSelezionati : List<String>
        - saveAppuntamentoFrom : String
        - sendSmsClienteNominativo : boolean
        - sendSmsOperatoreAssegnato : boolean
        + canAddAppuntamentoFromClienteNominativo()
        + canViewPraticaOrNominativo()
        + changeFromDate()
        + changeToDate()
        + checkAppuntamentiPresentiBeforeSave()
        + completeClientiNominativi()
        + concatNomeCognome()
        + deleteAppuntamento()
        + getAziendaSelectionView()
        + getCalendarioAppuntamentoService()
        + getCalendarioAppuntamentoViewModel()
        + getClienteManagerService()
        + getDateConversionUtil()
        + getHttpSessionUtil()
        + getLazyEventModel()
        + getOperatoriSelezionati()
        + getPassaggioParametriUtils()
        + getPraticheListByCliente()
        + getPropertiesUtil()
        + getSaveAppuntamentoFrom()
        + getSearchService()
        + getSelectedPratica()
        + getSettingService()
        + init()
        + isAppuntamentoLiberoRendered()
        + isClienteNominativoRendered()
        + isDeleteAppuntamentiButtonRendered()
        + isNominativoRendered()
        + isPraticaRendered()
        + isRenderedNotificaSmsInFormsCliente()
        + isRenderedNotificaSmsInFormsNominativo()
        + isSaveAppuntamentiButtonRendered()
        + isSelectCheckboxMenuRendered()
        + isSendSmsClienteNominativo()
        + isSendSmsOperatoreAssegnato()
        + onDateSelect()
        + onEventMove()
        + onEventResize()
        + onEventSelect()
        + onFlowProcess()
        + onRowSelect()
        + redirectToClienteOrNominativoForm()
        + resetAppuntamento()
        + resetAppuntamentoPraticaSelezionataAndWizard()
        + saveAppuntamento()
        + setAziendaSelectionView()
        + setCalendarioAppuntamentoService()
        + setCalendarioAppuntamentoViewModel()
        + setClienteManagerService()
        + setDateConversionUtil()
        + setHttpSessionUtil()
        + setLazyEventModel()
        + setOperatoriSelezionati()
        + setPassaggioParametriUtils()
        + setPropertiesUtil()
        + setSaveAppuntamentoFrom()
        + setSearchService()
        + setSelectedPratica()
        + setSendSmsClienteNominativo()
        + setSendSmsOperatoreAssegnato()
        + setSettingService()
        - getOperatoreAssegnato()
        - hasAuthorityReadAppuntamento()
        - isAppuntamentiButtonRendered()
        - onEventResizeOrMove()
        - saveAppuntamentoAndCheckResultFromPraticaOrNominativo()
        - saveAppuntamentoAndSendSms()
        - saveAppuntamentoAndSendSmsFromDashboard()
        - saveAppuntamentoFromDashboard()
        - saveAppuntamentoFromPraticaOrNominativo()
        - setPraticaIntoCalendarioAppuntamenti()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.calendarioappuntamenti {
    class com.woonders.lacemsjsf.view.calendarioappuntamenti.DateRangeValidator {
        + DateRangeValidator()
        + getPropertiesUtil()
        + setPropertiesUtil()
        + validate()
    }
  }
  

  com.woonders.lacemsjsf.view.calendarioappuntamenti.CalendarioAppuntamentiView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.calendarioappuntamenti.DateRangeValidator -up-|> com.woonders.lacemsjsf.util.BaseValidator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
