@startuml

title __DETTAGLIDOC's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.request {
        namespace dettaglidoc {
          class com.woonders.lacemscommon.fattureincloud.network.request.dettaglidoc.DettagliDocRequestBody {
              + id : String
              + token : String
              + DettagliDocRequestBody()
              + DettagliDocRequestBody()
              {static} + builder()
              + getId()
              + getToken()
              + setId()
              + setToken()
              + toString()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.request {
        namespace dettaglidoc {
          class com.woonders.lacemscommon.fattureincloud.network.request.dettaglidoc.DettagliDocRequestBody.DettagliDocRequestBodyBuilder {
              - id : String
              - token : String
              + build()
              + id()
              + toString()
              + token()
              ~ DettagliDocRequestBodyBuilder()
          }
        }
      }
    }
  }
  

  com.woonders.lacemscommon.fattureincloud.network.request.dettaglidoc.DettagliDocRequestBody -up-|> com.woonders.lacemscommon.fattureincloud.network.request.BaseRequestBody
  com.woonders.lacemscommon.fattureincloud.network.request.dettaglidoc.DettagliDocRequestBody +-down- com.woonders.lacemscommon.fattureincloud.network.request.dettaglidoc.DettagliDocRequestBody.DettagliDocRequestBodyBuilder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
