@startuml

title __MODEL's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.AdvancedSearch {
          - aziendaId : Long
          - dataAssunzione : Date
          - dataDecorrenzaFine : Date
          - dataDecorrenzaInizio : Date
          - dataDeliberaFine : Date
          - dataDeliberaInizio : Date
          - dataFineCaricamento : Date
          - dataFineInserimento : Date
          - dataFirmaContrattiFine : Date
          - dataFirmaContrattiInizio : Date
          - dataInizioCaricamento : Date
          - dataInizioInserimento : Date
          - dataIstruitaFine : Date
          - dataIstruitaInizio : Date
          - dataIstruttoriaFine : Date
          - dataIstruttoriaInizio : Date
          - dataLiquidazioneFine : Date
          - dataLiquidazioneInizio : Date
          - dataNascitaFine : Date
          - dataNascitaInizio : Date
          - dataPerfezionamentoFine : Date
          - dataPerfezionamentoInizio : Date
          - dataRecallFine : Date
          - dataRecallInizio : Date
          - dataRinnovoFine : Date
          - dataRinnovoInizio : Date
          - impieghiList : List<String>
          - operatorList : List<String>
          - provenienzaList : List<String>
          - provinciaResidenza : String
          - statoNominativoList : List<String>
          - statoPraticaList : List<String>
          + AdvancedSearch()
          + AdvancedSearch()
          {static} + builder()
          + getAmministrazione()
          + getAziendaId()
          + getDataAssunzione()
          + getDataDecorrenzaFine()
          + getDataDecorrenzaInizio()
          + getDataDeliberaFine()
          + getDataDeliberaInizio()
          + getDataFineCaricamento()
          + getDataFineInserimento()
          + getDataFirmaContrattiFine()
          + getDataFirmaContrattiInizio()
          + getDataInizioCaricamento()
          + getDataInizioInserimento()
          + getDataIstruitaFine()
          + getDataIstruitaInizio()
          + getDataIstruttoriaFine()
          + getDataIstruttoriaInizio()
          + getDataLiquidazioneFine()
          + getDataLiquidazioneInizio()
          + getDataNascitaFine()
          + getDataNascitaInizio()
          + getDataPerfezionamentoFine()
          + getDataPerfezionamentoInizio()
          + getDataRecallFine()
          + getDataRecallInizio()
          + getDataRinnovoFine()
          + getDataRinnovoInizio()
          + getImpieghiList()
          + getOperatorList()
          + getProvenienzaList()
          + getProvinciaResidenza()
          + getSesso()
          + getStatoNominativoList()
          + getStatoPraticaList()
          + getTipoRinnovo()
          + setAmministrazione()
          + setAziendaId()
          + setDataAssunzione()
          + setDataDecorrenzaFine()
          + setDataDecorrenzaInizio()
          + setDataDeliberaFine()
          + setDataDeliberaInizio()
          + setDataFineCaricamento()
          + setDataFineInserimento()
          + setDataFirmaContrattiFine()
          + setDataFirmaContrattiInizio()
          + setDataInizioCaricamento()
          + setDataInizioInserimento()
          + setDataIstruitaFine()
          + setDataIstruitaInizio()
          + setDataIstruttoriaFine()
          + setDataIstruttoriaInizio()
          + setDataLiquidazioneFine()
          + setDataLiquidazioneInizio()
          + setDataNascitaFine()
          + setDataNascitaInizio()
          + setDataPerfezionamentoFine()
          + setDataPerfezionamentoInizio()
          + setDataRecallFine()
          + setDataRecallInizio()
          + setDataRinnovoFine()
          + setDataRinnovoInizio()
          + setImpieghiList()
          + setOperatorList()
          + setProvenienzaList()
          + setProvinciaResidenza()
          + setSesso()
          + setStatoNominativoList()
          + setStatoPraticaList()
          + setTipoRinnovo()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.AdvancedSearch.AdvancedSearchBuilder {
          - aziendaId : Long
          - dataAssunzione : Date
          - dataDecorrenzaFine : Date
          - dataDecorrenzaInizio : Date
          - dataDeliberaFine : Date
          - dataDeliberaInizio : Date
          - dataFineCaricamento : Date
          - dataFineInserimento : Date
          - dataFirmaContrattiFine : Date
          - dataFirmaContrattiInizio : Date
          - dataInizioCaricamento : Date
          - dataInizioInserimento : Date
          - dataIstruitaFine : Date
          - dataIstruitaInizio : Date
          - dataIstruttoriaFine : Date
          - dataIstruttoriaInizio : Date
          - dataLiquidazioneFine : Date
          - dataLiquidazioneInizio : Date
          - dataNascitaFine : Date
          - dataNascitaInizio : Date
          - dataPerfezionamentoFine : Date
          - dataPerfezionamentoInizio : Date
          - dataRecallFine : Date
          - dataRecallInizio : Date
          - dataRinnovoFine : Date
          - dataRinnovoInizio : Date
          - impieghiList : List<String>
          - operatorList : List<String>
          - provenienzaList : List<String>
          - provinciaResidenza : String
          - statoNominativoList : List<String>
          - statoPraticaList : List<String>
          + amministrazione()
          + aziendaId()
          + build()
          + dataAssunzione()
          + dataDecorrenzaFine()
          + dataDecorrenzaInizio()
          + dataDeliberaFine()
          + dataDeliberaInizio()
          + dataFineCaricamento()
          + dataFineInserimento()
          + dataFirmaContrattiFine()
          + dataFirmaContrattiInizio()
          + dataInizioCaricamento()
          + dataInizioInserimento()
          + dataIstruitaFine()
          + dataIstruitaInizio()
          + dataIstruttoriaFine()
          + dataIstruttoriaInizio()
          + dataLiquidazioneFine()
          + dataLiquidazioneInizio()
          + dataNascitaFine()
          + dataNascitaInizio()
          + dataPerfezionamentoFine()
          + dataPerfezionamentoInizio()
          + dataRecallFine()
          + dataRecallInizio()
          + dataRinnovoFine()
          + dataRinnovoInizio()
          + impieghiList()
          + operatorList()
          + provenienzaList()
          + provinciaResidenza()
          + sesso()
          + statoNominativoList()
          + statoPraticaList()
          + tipoRinnovo()
          + toString()
          ~ AdvancedSearchBuilder()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.AdvancedSearchViewModel {
          - anniAssunzione : Integer
          - aziendaId : Long
          - dataDecorrenzaFine : LocalDate
          - dataDecorrenzaInizio : LocalDate
          - dataDeliberaFine : LocalDate
          - dataDeliberaInizio : LocalDate
          - dataFineCaricamento : LocalDate
          - dataFineInserimento : LocalDate
          - dataFirmaContrattiFine : LocalDate
          - dataFirmaContrattiInizio : LocalDate
          - dataInizioCaricamento : LocalDate
          - dataInizioInserimento : LocalDate
          - dataIstruitaFine : LocalDate
          - dataIstruitaInizio : LocalDate
          - dataIstruttoriaFine : LocalDate
          - dataIstruttoriaInizio : LocalDate
          - dataLiquidazioneFine : LocalDate
          - dataLiquidazioneInizio : LocalDate
          - dataPerfezionamentoFine : LocalDate
          - dataPerfezionamentoInizio : LocalDate
          - dataRecallFine : LocalDateTime
          - dataRecallInizio : LocalDateTime
          - dataRinnovoFine : LocalDate
          - dataRinnovoInizio : LocalDate
          - etaFrom : Integer
          - etaTo : Integer
          - impieghiList : List<String>
          - operatorList : List<String>
          - provenienzaList : List<String>
          - provinciaResidenza : String
          - statoNominativoList : List<String>
          - statoPraticaList : List<String>
          + AdvancedSearchViewModel()
          + AdvancedSearchViewModel()
          {static} + builder()
          + getAmministrazioneViewModel()
          + getAnniAssunzione()
          + getAziendaId()
          + getDataDecorrenzaFine()
          + getDataDecorrenzaInizio()
          + getDataDeliberaFine()
          + getDataDeliberaInizio()
          + getDataFineCaricamento()
          + getDataFineInserimento()
          + getDataFirmaContrattiFine()
          + getDataFirmaContrattiInizio()
          + getDataInizioCaricamento()
          + getDataInizioInserimento()
          + getDataIstruitaFine()
          + getDataIstruitaInizio()
          + getDataIstruttoriaFine()
          + getDataIstruttoriaInizio()
          + getDataLiquidazioneFine()
          + getDataLiquidazioneInizio()
          + getDataPerfezionamentoFine()
          + getDataPerfezionamentoInizio()
          + getDataRecallFine()
          + getDataRecallInizio()
          + getDataRinnovoFine()
          + getDataRinnovoInizio()
          + getEtaFrom()
          + getEtaTo()
          + getImpieghiList()
          + getOperatorList()
          + getProvenienzaList()
          + getProvinciaResidenza()
          + getSesso()
          + getStatoNominativoList()
          + getStatoPraticaList()
          + getTipoRinnovo()
          + setAmministrazioneViewModel()
          + setAnniAssunzione()
          + setAziendaId()
          + setDataDecorrenzaFine()
          + setDataDecorrenzaInizio()
          + setDataDeliberaFine()
          + setDataDeliberaInizio()
          + setDataFineCaricamento()
          + setDataFineInserimento()
          + setDataFirmaContrattiFine()
          + setDataFirmaContrattiInizio()
          + setDataInizioCaricamento()
          + setDataInizioInserimento()
          + setDataIstruitaFine()
          + setDataIstruitaInizio()
          + setDataIstruttoriaFine()
          + setDataIstruttoriaInizio()
          + setDataLiquidazioneFine()
          + setDataLiquidazioneInizio()
          + setDataPerfezionamentoFine()
          + setDataPerfezionamentoInizio()
          + setDataRecallFine()
          + setDataRecallInizio()
          + setDataRinnovoFine()
          + setDataRinnovoInizio()
          + setEtaFrom()
          + setEtaTo()
          + setImpieghiList()
          + setOperatorList()
          + setProvenienzaList()
          + setProvinciaResidenza()
          + setSesso()
          + setStatoNominativoList()
          + setStatoPraticaList()
          + setTipoRinnovo()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.AdvancedSearchViewModel.AdvancedSearchViewModelBuilder {
          - anniAssunzione : Integer
          - aziendaId : Long
          - dataDecorrenzaFine : LocalDate
          - dataDecorrenzaInizio : LocalDate
          - dataDeliberaFine : LocalDate
          - dataDeliberaInizio : LocalDate
          - dataFineCaricamento : LocalDate
          - dataFineInserimento : LocalDate
          - dataFirmaContrattiFine : LocalDate
          - dataFirmaContrattiInizio : LocalDate
          - dataInizioCaricamento : LocalDate
          - dataInizioInserimento : LocalDate
          - dataIstruitaFine : LocalDate
          - dataIstruitaInizio : LocalDate
          - dataIstruttoriaFine : LocalDate
          - dataIstruttoriaInizio : LocalDate
          - dataLiquidazioneFine : LocalDate
          - dataLiquidazioneInizio : LocalDate
          - dataPerfezionamentoFine : LocalDate
          - dataPerfezionamentoInizio : LocalDate
          - dataRecallFine : LocalDateTime
          - dataRecallInizio : LocalDateTime
          - dataRinnovoFine : LocalDate
          - dataRinnovoInizio : LocalDate
          - etaFrom : Integer
          - etaTo : Integer
          - impieghiList : List<String>
          - operatorList : List<String>
          - provenienzaList : List<String>
          - provinciaResidenza : String
          - statoNominativoList : List<String>
          - statoPraticaList : List<String>
          + amministrazioneViewModel()
          + anniAssunzione()
          + aziendaId()
          + build()
          + dataDecorrenzaFine()
          + dataDecorrenzaInizio()
          + dataDeliberaFine()
          + dataDeliberaInizio()
          + dataFineCaricamento()
          + dataFineInserimento()
          + dataFirmaContrattiFine()
          + dataFirmaContrattiInizio()
          + dataInizioCaricamento()
          + dataInizioInserimento()
          + dataIstruitaFine()
          + dataIstruitaInizio()
          + dataIstruttoriaFine()
          + dataIstruttoriaInizio()
          + dataLiquidazioneFine()
          + dataLiquidazioneInizio()
          + dataPerfezionamentoFine()
          + dataPerfezionamentoInizio()
          + dataRecallFine()
          + dataRecallInizio()
          + dataRinnovoFine()
          + dataRinnovoInizio()
          + etaFrom()
          + etaTo()
          + impieghiList()
          + operatorList()
          + provenienzaList()
          + provinciaResidenza()
          + sesso()
          + statoNominativoList()
          + statoPraticaList()
          + tipoRinnovo()
          + toString()
          ~ AdvancedSearchViewModelBuilder()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.AnalyticsNominativiOperatore {
          - nominativiToClienti : long
          - nominativiTot : long
          - username : String
          + AnalyticsNominativiOperatore()
          + AnalyticsNominativiOperatore()
          {static} + builder()
          + getNominativiToClienti()
          + getNominativiTot()
          + getUsername()
          + setNominativiToClienti()
          + setNominativiTot()
          + setUsername()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.AnalyticsNominativiOperatore.AnalyticsNominativiOperatoreBuilder {
          - nominativiToClienti : long
          - nominativiTot : long
          - username : String
          + build()
          + nominativiToClienti()
          + nominativiTot()
          + toString()
          + username()
          ~ AnalyticsNominativiOperatoreBuilder()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.AnalyticsProvvigioneCliente {
          - ProvvigioneDlg : BigDecimal
          - provvigioneCqp : BigDecimal
          - provvigioneCqs : BigDecimal
          - provvigionePp : BigDecimal
          - provvigioneTot : BigDecimal
          - username : String
          + AnalyticsProvvigioneCliente()
          + AnalyticsProvvigioneCliente()
          {static} + builder()
          + getProvvigioneCqp()
          + getProvvigioneCqs()
          + getProvvigioneDlg()
          + getProvvigionePp()
          + getProvvigioneTot()
          + getUsername()
          + setProvvigioneCqp()
          + setProvvigioneCqs()
          + setProvvigioneDlg()
          + setProvvigionePp()
          + setProvvigioneTot()
          + setUsername()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.AnalyticsProvvigioneCliente.AnalyticsProvvigioneClienteBuilder {
          - ProvvigioneDlg : BigDecimal
          - provvigioneCqp : BigDecimal
          - provvigioneCqs : BigDecimal
          - provvigionePp : BigDecimal
          - provvigioneTot : BigDecimal
          - username : String
          + ProvvigioneDlg()
          + build()
          + provvigioneCqp()
          + provvigioneCqs()
          + provvigionePp()
          + provvigioneTot()
          + toString()
          + username()
          ~ AnalyticsProvvigioneClienteBuilder()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.AppuntamentoSavedResultBoolean {
          - appuntamentoSalvato : boolean
          - inviaNotificaClienteNominativo : boolean
          - inviaNotificaOperatore : boolean
          - smsInviatoClienteNominativo : boolean
          - smsInviatoOperatore : boolean
          - smsNotSentErrorClienteNominativo : boolean
          - smsNotSentErrorOperatore : boolean
          + AppuntamentoSavedResultBoolean()
          + AppuntamentoSavedResultBoolean()
          + isAppuntamentoSalvato()
          + isInviaNotificaClienteNominativo()
          + isInviaNotificaOperatore()
          + isSmsInviatoClienteNominativo()
          + isSmsInviatoOperatore()
          + isSmsNotSentErrorClienteNominativo()
          + isSmsNotSentErrorOperatore()
          + setAppuntamentoSalvato()
          + setInviaNotificaClienteNominativo()
          + setInviaNotificaOperatore()
          + setSmsInviatoClienteNominativo()
          + setSmsInviatoOperatore()
          + setSmsNotSentErrorClienteNominativo()
          + setSmsNotSentErrorOperatore()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.CalcSmsInfo {
          - destinatariCount : int
          - smsCount : int
          {static} + builder()
          + getDestinatariCount()
          + getSmsCount()
          + setDestinatariCount()
          + setSmsCount()
          ~ CalcSmsInfo()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.CalcSmsInfo.CalcSmsInfoBuilder {
          - destinatariCount : int
          - smsCount : int
          + build()
          + destinatariCount()
          + smsCount()
          + toString()
          ~ CalcSmsInfoBuilder()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.ClientePratica {
          + ClientePratica()
          + ClientePratica()
          {static} + builder()
          + equals()
          + getClienteViewModel()
          + getPraticaViewModel()
          + getTrattenuteViewModel()
          + hashCode()
          + setClienteViewModel()
          + setPraticaViewModel()
          + setTrattenuteViewModel()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.ClientePratica.ClientePraticaBuilder {
          + build()
          + clienteViewModel()
          + praticaViewModel()
          + toString()
          + trattenuteViewModel()
          ~ ClientePraticaBuilder()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.ClientePreventivo {
          + ClientePreventivo()
          + ClientePreventivo()
          {static} + builder()
          + equals()
          + getClienteViewModel()
          + getPreventivoViewModel()
          + hashCode()
          + setClienteViewModel()
          + setPreventivoViewModel()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.ClientePreventivo.ClientePreventivoBuilder {
          + build()
          + clienteViewModel()
          + preventivoViewModel()
          + toString()
          ~ ClientePreventivoBuilder()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.ClienteTrattenuta {
          + ClienteTrattenuta()
          + ClienteTrattenuta()
          {static} + builder()
          + equals()
          + getClienteViewModel()
          + getTrattenuteViewModel()
          + hashCode()
          + setClienteViewModel()
          + setTrattenuteViewModel()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.ClienteTrattenuta.ClienteTrattenutaBuilder {
          + build()
          + clienteViewModel()
          + toString()
          + trattenuteViewModel()
          ~ ClienteTrattenutaBuilder()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.EstinzionePraticaCliente {
          + EstinzionePraticaCliente()
          + EstinzionePraticaCliente()
          {static} + builder()
          + equals()
          + getClienteViewModel()
          + getEstinzioneViewModel()
          + getPraticaViewModel()
          + hashCode()
          + setClienteViewModel()
          + setEstinzioneViewModel()
          + setPraticaViewModel()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.EstinzionePraticaCliente.EstinzionePraticaClienteBuilder {
          + build()
          + clienteViewModel()
          + estinzioneViewModel()
          + praticaViewModel()
          + toString()
          ~ EstinzionePraticaClienteBuilder()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.PraticheInCorsoModel {
          - durata : Integer
          - rata : BigDecimal
          - tipoPratica : String
          + PraticheInCorsoModel()
          + equals()
          + getDurata()
          + getRata()
          + getTipoPratica()
          + hashCode()
          + setDurata()
          + setRata()
          + setTipoPratica()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.SimulatorResult {
          - agentFeesTotal : BigDecimal
          - amount : BigDecimal
          - amountTotal : BigDecimal
          - exceededAgentFees : boolean
          - exceededTaeg : boolean
          - interests : BigDecimal
          - length : int
          - payment : BigDecimal
          - taeg : BigDecimal
          - tan : BigDecimal
          - totalCosts : BigDecimal
          - upright : BigDecimal
          + SimulatorResult()
          + SimulatorResult()
          {static} + builder()
          + getAgentFeesTotal()
          + getAmount()
          + getAmountTotal()
          + getInterests()
          + getLength()
          + getPayment()
          + getTaeg()
          + getTan()
          + getTotalCosts()
          + getUpright()
          + isExceededAgentFees()
          + isExceededTaeg()
          + setAgentFeesTotal()
          + setAmount()
          + setAmountTotal()
          + setExceededAgentFees()
          + setExceededTaeg()
          + setInterests()
          + setLength()
          + setPayment()
          + setTaeg()
          + setTan()
          + setTotalCosts()
          + setUpright()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.SimulatorResult.SimulatorResultBuilder {
          - agentFeesTotal : BigDecimal
          - amount : BigDecimal
          - amountTotal : BigDecimal
          - exceededAgentFees : boolean
          - exceededTaeg : boolean
          - interests : BigDecimal
          - length : int
          - payment : BigDecimal
          - taeg : BigDecimal
          - tan : BigDecimal
          - totalCosts : BigDecimal
          - upright : BigDecimal
          + agentFeesTotal()
          + amount()
          + amountTotal()
          + build()
          + exceededAgentFees()
          + exceededTaeg()
          + interests()
          + length()
          + payment()
          + taeg()
          + tan()
          + toString()
          + totalCosts()
          + upright()
          ~ SimulatorResultBuilder()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      interface com.woonders.lacemscommon.app.model.ViewModelPage {
          {abstract} + getContent()
          {abstract} + getTotalElements()
          {abstract} + getTotalPages()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.ViewModelPageImpl {
          - content : List<T>
          - totalElements : long
          - totalPages : int
          + ViewModelPageImpl()
          {static} + builder()
          + getContent()
          + getTotalElements()
          + getTotalPages()
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace app.model {
      class com.woonders.lacemscommon.app.model.ViewModelPageImpl.ViewModelPageImplBuilder {
          - content : List<T>
          - totalElements : long
          - totalPages : int
          + build()
          + content()
          + toString()
          + totalElements()
          + totalPages()
          ~ ViewModelPageImplBuilder()
      }
    }
  }
  

  com.woonders.lacemscommon.app.model.AdvancedSearch o-- com.woonders.lacemscommon.db.entity.Amministrazione : amministrazione
  com.woonders.lacemscommon.app.model.AdvancedSearch o-- com.woonders.lacemscommon.db.entity.Cliente.Sesso : sesso
  com.woonders.lacemscommon.app.model.AdvancedSearch o-- com.woonders.lacemscommon.laceenum.TipoRinnovo : tipoRinnovo
  com.woonders.lacemscommon.app.model.AdvancedSearch +-down- com.woonders.lacemscommon.app.model.AdvancedSearch.AdvancedSearchBuilder
  com.woonders.lacemscommon.app.model.AdvancedSearch.AdvancedSearchBuilder o-- com.woonders.lacemscommon.db.entity.Amministrazione : amministrazione
  com.woonders.lacemscommon.app.model.AdvancedSearch.AdvancedSearchBuilder o-- com.woonders.lacemscommon.db.entity.Cliente.Sesso : sesso
  com.woonders.lacemscommon.app.model.AdvancedSearch.AdvancedSearchBuilder o-- com.woonders.lacemscommon.laceenum.TipoRinnovo : tipoRinnovo
  com.woonders.lacemscommon.app.model.AdvancedSearchViewModel o-- com.woonders.lacemscommon.app.viewmodel.AmministrazioneViewModel : amministrazioneViewModel
  com.woonders.lacemscommon.app.model.AdvancedSearchViewModel o-- com.woonders.lacemscommon.db.entity.Cliente.Sesso : sesso
  com.woonders.lacemscommon.app.model.AdvancedSearchViewModel o-- com.woonders.lacemscommon.laceenum.TipoRinnovo : tipoRinnovo
  com.woonders.lacemscommon.app.model.AdvancedSearchViewModel +-down- com.woonders.lacemscommon.app.model.AdvancedSearchViewModel.AdvancedSearchViewModelBuilder
  com.woonders.lacemscommon.app.model.AdvancedSearchViewModel.AdvancedSearchViewModelBuilder o-- com.woonders.lacemscommon.app.viewmodel.AmministrazioneViewModel : amministrazioneViewModel
  com.woonders.lacemscommon.app.model.AdvancedSearchViewModel.AdvancedSearchViewModelBuilder o-- com.woonders.lacemscommon.db.entity.Cliente.Sesso : sesso
  com.woonders.lacemscommon.app.model.AdvancedSearchViewModel.AdvancedSearchViewModelBuilder o-- com.woonders.lacemscommon.laceenum.TipoRinnovo : tipoRinnovo
  com.woonders.lacemscommon.app.model.AnalyticsNominativiOperatore +-down- com.woonders.lacemscommon.app.model.AnalyticsNominativiOperatore.AnalyticsNominativiOperatoreBuilder
  com.woonders.lacemscommon.app.model.AnalyticsProvvigioneCliente +-down- com.woonders.lacemscommon.app.model.AnalyticsProvvigioneCliente.AnalyticsProvvigioneClienteBuilder
  com.woonders.lacemscommon.app.model.CalcSmsInfo +-down- com.woonders.lacemscommon.app.model.CalcSmsInfo.CalcSmsInfoBuilder
  com.woonders.lacemscommon.app.model.ClientePratica o-- com.woonders.lacemscommon.app.viewmodel.ClienteViewModel : clienteViewModel
  com.woonders.lacemscommon.app.model.ClientePratica o-- com.woonders.lacemscommon.app.viewmodel.PraticaViewModel : praticaViewModel
  com.woonders.lacemscommon.app.model.ClientePratica o-- com.woonders.lacemscommon.app.viewmodel.TrattenuteViewModel : trattenuteViewModel
  com.woonders.lacemscommon.app.model.ClientePratica +-down- com.woonders.lacemscommon.app.model.ClientePratica.ClientePraticaBuilder
  com.woonders.lacemscommon.app.model.ClientePratica.ClientePraticaBuilder o-- com.woonders.lacemscommon.app.viewmodel.ClienteViewModel : clienteViewModel
  com.woonders.lacemscommon.app.model.ClientePratica.ClientePraticaBuilder o-- com.woonders.lacemscommon.app.viewmodel.PraticaViewModel : praticaViewModel
  com.woonders.lacemscommon.app.model.ClientePratica.ClientePraticaBuilder o-- com.woonders.lacemscommon.app.viewmodel.TrattenuteViewModel : trattenuteViewModel
  com.woonders.lacemscommon.app.model.ClientePreventivo o-- com.woonders.lacemscommon.app.viewmodel.ClienteViewModel : clienteViewModel
  com.woonders.lacemscommon.app.model.ClientePreventivo o-- com.woonders.lacemscommon.app.viewmodel.PreventivoViewModel : preventivoViewModel
  com.woonders.lacemscommon.app.model.ClientePreventivo +-down- com.woonders.lacemscommon.app.model.ClientePreventivo.ClientePreventivoBuilder
  com.woonders.lacemscommon.app.model.ClientePreventivo.ClientePreventivoBuilder o-- com.woonders.lacemscommon.app.viewmodel.ClienteViewModel : clienteViewModel
  com.woonders.lacemscommon.app.model.ClientePreventivo.ClientePreventivoBuilder o-- com.woonders.lacemscommon.app.viewmodel.PreventivoViewModel : preventivoViewModel
  com.woonders.lacemscommon.app.model.ClienteTrattenuta o-- com.woonders.lacemscommon.app.viewmodel.ClienteViewModel : clienteViewModel
  com.woonders.lacemscommon.app.model.ClienteTrattenuta o-- com.woonders.lacemscommon.app.viewmodel.TrattenuteViewModel : trattenuteViewModel
  com.woonders.lacemscommon.app.model.ClienteTrattenuta +-down- com.woonders.lacemscommon.app.model.ClienteTrattenuta.ClienteTrattenutaBuilder
  com.woonders.lacemscommon.app.model.ClienteTrattenuta.ClienteTrattenutaBuilder o-- com.woonders.lacemscommon.app.viewmodel.ClienteViewModel : clienteViewModel
  com.woonders.lacemscommon.app.model.ClienteTrattenuta.ClienteTrattenutaBuilder o-- com.woonders.lacemscommon.app.viewmodel.TrattenuteViewModel : trattenuteViewModel
  com.woonders.lacemscommon.app.model.EstinzionePraticaCliente o-- com.woonders.lacemscommon.app.viewmodel.ClienteViewModel : clienteViewModel
  com.woonders.lacemscommon.app.model.EstinzionePraticaCliente o-- com.woonders.lacemscommon.app.viewmodel.EstinzioneViewModel : estinzioneViewModel
  com.woonders.lacemscommon.app.model.EstinzionePraticaCliente o-- com.woonders.lacemscommon.app.viewmodel.PraticaViewModel : praticaViewModel
  com.woonders.lacemscommon.app.model.EstinzionePraticaCliente +-down- com.woonders.lacemscommon.app.model.EstinzionePraticaCliente.EstinzionePraticaClienteBuilder
  com.woonders.lacemscommon.app.model.EstinzionePraticaCliente.EstinzionePraticaClienteBuilder o-- com.woonders.lacemscommon.app.viewmodel.ClienteViewModel : clienteViewModel
  com.woonders.lacemscommon.app.model.EstinzionePraticaCliente.EstinzionePraticaClienteBuilder o-- com.woonders.lacemscommon.app.viewmodel.EstinzioneViewModel : estinzioneViewModel
  com.woonders.lacemscommon.app.model.EstinzionePraticaCliente.EstinzionePraticaClienteBuilder o-- com.woonders.lacemscommon.app.viewmodel.PraticaViewModel : praticaViewModel
  com.woonders.lacemscommon.app.model.SimulatorResult +-down- com.woonders.lacemscommon.app.model.SimulatorResult.SimulatorResultBuilder
  com.woonders.lacemscommon.app.model.ViewModelPageImpl .up.|> com.woonders.lacemscommon.app.model.ViewModelPage
  com.woonders.lacemscommon.app.model.ViewModelPageImpl +-down- com.woonders.lacemscommon.app.model.ViewModelPageImpl.ViewModelPageImplBuilder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
