@startuml

title __EXCEPTION's Class Diagram__\n

  namespace com.woonders.lacemsjsf.exception {
    class com.woonders.lacemsjsf.exception.AmministrazioneNotExistsException {
        {static} - serialVersionUID : long
        + AmministrazioneNotExistsException()
        + AmministrazioneNotExistsException()
        + AmministrazioneNotExistsException()
        + AmministrazioneNotExistsException()
        + AmministrazioneNotExistsException()
    }
  }
  

  namespace com.woonders.lacemsjsf.exception {
    class com.woonders.lacemsjsf.exception.CoobbligatoNotDeleteException {
        {static} - serialVersionUID : long
        + CoobbligatoNotDeleteException()
        + CoobbligatoNotDeleteException()
        + CoobbligatoNotDeleteException()
        + CoobbligatoNotDeleteException()
        + CoobbligatoNotDeleteException()
    }
  }
  

  namespace com.woonders.lacemsjsf.exception {
    class com.woonders.lacemsjsf.exception.DataSourceNotFoundException {
        + DataSourceNotFoundException()
        + DataSourceNotFoundException()
        + DataSourceNotFoundException()
        + DataSourceNotFoundException()
        + DataSourceNotFoundException()
    }
  }
  

  namespace com.woonders.lacemsjsf.exception {
    class com.woonders.lacemsjsf.exception.FieldPdfNotFoundException {
        {static} - serialVersionUID : long
        + FieldPdfNotFoundException()
        + FieldPdfNotFoundException()
        + FieldPdfNotFoundException()
        + FieldPdfNotFoundException()
        + FieldPdfNotFoundException()
    }
  }
  

  namespace com.woonders.lacemsjsf.exception {
    class com.woonders.lacemsjsf.exception.FunctionalityNotEnabledException {
        + FunctionalityNotEnabledException()
        + FunctionalityNotEnabledException()
        + FunctionalityNotEnabledException()
        + FunctionalityNotEnabledException()
        + FunctionalityNotEnabledException()
    }
  }
  

  namespace com.woonders.lacemsjsf.exception {
    class com.woonders.lacemsjsf.exception.NoFileOnS3Exception {
        - byteArrayOutputStreamDefaultContent : ByteArrayOutputStream
        + NoFileOnS3Exception()
        + NoFileOnS3Exception()
        + NoFileOnS3Exception()
        + NoFileOnS3Exception()
        + NoFileOnS3Exception()
        + NoFileOnS3Exception()
        + getByteArrayOutputStreamDefaultContent()
    }
  }
  

  namespace com.woonders.lacemsjsf.exception {
    class com.woonders.lacemsjsf.exception.NoSuchSessionException {
        {static} - serialVersionUID : long
    }
  }
  

  namespace com.woonders.lacemsjsf.exception {
    class com.woonders.lacemsjsf.exception.NuovaPraticaDaPreventivoNotSavedException {
        {static} - serialVersionUID : long
        + NuovaPraticaDaPreventivoNotSavedException()
        + NuovaPraticaDaPreventivoNotSavedException()
        + NuovaPraticaDaPreventivoNotSavedException()
        + NuovaPraticaDaPreventivoNotSavedException()
        + NuovaPraticaDaPreventivoNotSavedException()
    }
  }
  

  namespace com.woonders.lacemsjsf.exception {
    class com.woonders.lacemsjsf.exception.OutOfStorageException {
        + OutOfStorageException()
        + OutOfStorageException()
        + OutOfStorageException()
        + OutOfStorageException()
        + OutOfStorageException()
    }
  }
  

  namespace com.woonders.lacemsjsf.exception {
    class com.woonders.lacemsjsf.exception.PreventivoNotDeleteException {
        {static} - serialVersionUID : long
        + PreventivoNotDeleteException()
        + PreventivoNotDeleteException()
        + PreventivoNotDeleteException()
        + PreventivoNotDeleteException()
        + PreventivoNotDeleteException()
    }
  }
  

  namespace com.woonders.lacemsjsf.exception {
    class com.woonders.lacemsjsf.exception.PreventivoPraticaNotSavedException {
        {static} - serialVersionUID : long
        + PreventivoPraticaNotSavedException()
        + PreventivoPraticaNotSavedException()
        + PreventivoPraticaNotSavedException()
        + PreventivoPraticaNotSavedException()
        + PreventivoPraticaNotSavedException()
    }
  }
  

  namespace com.woonders.lacemsjsf.exception {
    class com.woonders.lacemsjsf.exception.PreventivoTrattenutaNotSavedException {
        {static} - serialVersionUID : long
        + PreventivoTrattenutaNotSavedException()
        + PreventivoTrattenutaNotSavedException()
        + PreventivoTrattenutaNotSavedException()
        + PreventivoTrattenutaNotSavedException()
        + PreventivoTrattenutaNotSavedException()
    }
  }
  

  namespace com.woonders.lacemsjsf.exception {
    class com.woonders.lacemsjsf.exception.SessionExpiredException {
        + SessionExpiredException()
        + SessionExpiredException()
        + SessionExpiredException()
        + SessionExpiredException()
        + SessionExpiredException()
    }
  }
  

  namespace com.woonders.lacemsjsf.exception {
    class com.woonders.lacemsjsf.exception.UserNotFoundException {
        {static} - serialVersionUID : long
    }
  }
  

  namespace com.woonders.lacemsjsf.exception {
    class com.woonders.lacemsjsf.exception.ValutazioneNotDeleteException {
        {static} - serialVersionUID : long
        + ValutazioneNotDeleteException()
        + ValutazioneNotDeleteException()
        + ValutazioneNotDeleteException()
        + ValutazioneNotDeleteException()
        + ValutazioneNotDeleteException()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
