@startuml

title __PRATICA's Class Diagram__\n

  namespace com.woonders.lacemsjsf.view.pratica {
    class com.woonders.lacemsjsf.view.pratica.PraticaView {
        {static} + JSF_NAME : String
        {static} + NAME : String
        + calcConteggioEstinzioneTotale()
        + calcDataRinnovo()
        + calcDebitoResiduo()
        + calcInteressi()
        + calcMontante()
        + calcNettoMensile()
        + calcNettoRicavo()
        + calcPercProv()
        + calcProvTotale()
        + calcRateScadenzaPratica()
        + calcScadenzaPratica()
        + isDataPerfezionamentoRendered()
        + isSimulatorTableUsed()
        + isTipoPraticaNotSelected()
        + removeEstinzione()
        + resetEstinzione()
        + resetProvvigioneEuro()
        + setClienteManagerService()
        + setEstinzioneUtil()
        + setEstinzioneView()
        + setHttpSessionUtil()
        + setPraticaUtil()
        + setPropertiesUtil()
        + updateDatiEstinzioneAndPraticaFromScadenza()
        + updateDatiEstinzioneFromDataBustaPaga()
        + updateDatiPraticaFromDecorrenza()
        - resetEstinzione()
    }
  }
  

  com.woonders.lacemsjsf.view.pratica.PraticaView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.pratica.PraticaView o-- com.woonders.lacemscommon.service.ClienteManagerService : clienteManagerService
  com.woonders.lacemsjsf.view.pratica.PraticaView o-- com.woonders.lacemscommon.db.entityutil.EstinzioneUtil : estinzioneUtil
  com.woonders.lacemsjsf.view.pratica.PraticaView o-- com.woonders.lacemsjsf.view.estinzione.EstinzioneView : estinzioneView
  com.woonders.lacemsjsf.view.pratica.PraticaView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.pratica.PraticaView o-- com.woonders.lacemscommon.db.entityutil.PraticaUtil : praticaUtil
  com.woonders.lacemsjsf.view.pratica.PraticaView o-- com.woonders.lacemsjsf.config.PropertiesUtil : propertiesUtil


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
