@startuml

title __NOMINATIVO's Class Diagram__\n

  namespace com.woonders.lacemsjsf.view.nominativo {
    class com.woonders.lacemsjsf.view.nominativo.CheckNominativo {
        {static} + JSF_NAME : String
        {static} + NAME : String
        - cf : String
        - cognome : String
        - dataNascita : Date
        - email : String
        - luogoNascita : String
        - nome : String
        - telefonoCellulare : String
        - telefonoFisso : String
        + getCalcCf()
        + getCf()
        + getCfGenerator()
        + getCheckNominativoService()
        + getCognome()
        + getDataNascita()
        + getEmail()
        + getLuogoNascita()
        + getNome()
        + getPassaggioParametriUtils()
        + getPropertiesUtil()
        + getSesso()
        + getTelefonoCellulare()
        + getTelefonoFisso()
        + nominativoChecker()
        + setCf()
        + setCfGenerator()
        + setCheckNominativoService()
        + setCognome()
        + setDataNascita()
        + setEmail()
        + setLuogoNascita()
        + setNome()
        + setPassaggioParametriUtils()
        + setPropertiesUtil()
        + setSesso()
        + setTelefonoCellulare()
        + setTelefonoFisso()
        - setDatiNominativoInPassaggioParametri()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.nominativo {
    class com.woonders.lacemsjsf.view.nominativo.DashboardNominativo {
        {static} + JSF_NAME : String
        {static} + NAME : String
        - clienteViewModelLazyDataModel : LazyDataModel<ClienteViewModel>
        - dateRecall : Date
        + DashboardNominativo()
        + equals()
        + getAziendaSelectionView()
        + getAziendaService()
        + getClienteViewModelLazyDataModel()
        + getDashboardNominativoService()
        + getDateRecall()
        + getHttpSessionUtil()
        + getNominativoService()
        + getPassaggioParametriUtils()
        + getSelectedNominativo()
        + hashCode()
        + init()
        + listRecall()
        + onDateSelect()
        + onRowSelect()
        + setAziendaSelectionView()
        + setAziendaService()
        + setClienteViewModelLazyDataModel()
        + setDashboardNominativoService()
        + setDateRecall()
        + setHttpSessionUtil()
        + setNominativoService()
        + setPassaggioParametriUtils()
        + setSelectedNominativo()
        + toString()
        + viewNominativiDaLavorare()
        + viewNominativiOmessi()
        + viewRinnovoImpegni()
        # canEqual()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.nominativo {
    class com.woonders.lacemsjsf.view.nominativo.DatatableCheckNominativo {
        - cognome : String
        - data : Date
        - luogo : String
        - nome : String
        - nominativiViewModelList : List<ClienteViewModel>
        - telefonoCellulare : String
        - telefonoFisso : String
        + getCheckNominativoService()
        + getCheckPermissionUtils()
        + getCognome()
        + getData()
        + getHttpSessionUtil()
        + getLuogo()
        + getNome()
        + getNominativiViewModelList()
        + getNominativoService()
        + getPassaggioParametriUtils()
        + getPropertiesUtil()
        + getSelectedNominativoViewModel()
        + getSesso()
        + getTelefonoCellulare()
        + getTelefonoFisso()
        + goToFormsNominativo()
        + init()
        + onRowSelect()
        + setCheckNominativoService()
        + setCheckPermissionUtils()
        + setCognome()
        + setData()
        + setHttpSessionUtil()
        + setLuogo()
        + setNome()
        + setNominativiViewModelList()
        + setNominativoService()
        + setPassaggioParametriUtils()
        + setPropertiesUtil()
        + setSelectedNominativoViewModel()
        + setSesso()
        + setTelefonoCellulare()
        + setTelefonoFisso()
        + valueOfOperator()
        - checkNominativi()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.nominativo {
    class com.woonders.lacemsjsf.view.nominativo.DatatableNominativiOmessiView {
        {static} + JSF_NAME : String
        {static} + NAME : String
        - clienteViewModelLazyDataModel : LazyDataModel<ClienteViewModel>
        + getAziendaSelectionView()
        + getClienteViewModelLazyDataModel()
        + getDashboardNominativoService()
        + getHttpSessionUtil()
        + getPassaggioParametriUtils()
        + getSelectedNominativoViewModel()
        + init()
        + onRowSelect()
        + setAziendaSelectionView()
        + setClienteViewModelLazyDataModel()
        + setDashboardNominativoService()
        + setHttpSessionUtil()
        + setNullDataRecall()
        + setPassaggioParametriUtils()
        + setSelectedNominativoViewModel()
        - retrieveNominativiByDataRecallExpired()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.nominativo {
    class com.woonders.lacemsjsf.view.nominativo.DatatableNominativoRinnoviView {
        {static} + JSF_NAME : String
        {static} + NAME : String
        - clienteTrattenutaLazyDataModel : LazyDataModel<ClienteTrattenuta>
        + DatatableNominativoRinnoviView()
        + equals()
        + getAziendaSelectionView()
        + getAziendaService()
        + getClienteTrattenutaLazyDataModel()
        + getDashboardNominativoService()
        + getHttpSessionUtil()
        + getPassaggioParametriUtils()
        + getSelectedClienteTrattenuta()
        + hashCode()
        + init()
        + onRowSelect()
        + setAziendaSelectionView()
        + setAziendaService()
        + setClienteTrattenutaLazyDataModel()
        + setDashboardNominativoService()
        + setHttpSessionUtil()
        + setNotiCoes()
        + setPassaggioParametriUtils()
        + setSelectedClienteTrattenuta()
        + toString()
        # canEqual()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.nominativo {
    class com.woonders.lacemsjsf.view.nominativo.NominativoPdfView {
        - file : ByteArrayOutputStream
        + NominativoPdfView()
        + getFile()
        + getIdFile()
        + getNominativoPdf()
        + getPassaggioParametriUtils()
        + getStream()
        + setFile()
        + setNominativoPdf()
        + setPassaggioParametriUtils()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.nominativo {
    class com.woonders.lacemsjsf.view.nominativo.Register {
        - amministrazioneViewModelList : List<AmministrazioneViewModel>
        - commentoLog : String
        - contestaNominativoCommento : String
        - impegniSelezionati : List<TrattenuteViewModel>
        {static} - log : Logger
        - motivoContestazione : int
        - preventivoList : List<PraticaViewModel>
        - smsText : String
        - trattenuteNominativoList : List<TrattenuteViewModel>
        + add()
        + addPreventiviToBody()
        + addPreventiviToBodySMS()
        + addPreventivoFromSimulatorResultRowChoosen()
        + addTratt()
        + calcReverseCf()
        + canWriteNominativo()
        + clearPassaggioParametriAmministrazione()
        + completeAmministrazione()
        + creaPratica()
        + deleteNominativo()
        + getAmministrazioneService()
        + getAmministrazioneViewModelList()
        + getArchiviazioneRendered()
        + getAziendaService()
        + getCfGenerator()
        + getClienteUtil()
        + getCommentoLog()
        + getContestaNominativoCommento()
        + getDataEsitoSmsNotificaLead()
        + getErrorConverter()
        + getEsitoSmsNotificaLead()
        + getExceptionResolverUtil()
        + getHttpSessionUtil()
        + getImpegniSelezionati()
        + getLaceMailSender()
        + getLogService()
        + getMailClient()
        + getMotivoContestazione()
        + getNominativo()
        + getNominativoService()
        + getNotificaLeadSmsViewModel()
        + getOperatorService()
        + getPassaggioParametriUtils()
        + getPdfPage()
        + getPreventivoDaCreare()
        + getPreventivoList()
        + getPropertiesUtil()
        + getRequestTenantIdentifierResolver()
        + getResidenzaViewModel()
        + getSettingService()
        + getSimulatorUtilsView()
        + getSmsServiceFacade()
        + getSmsText()
        + getTrattenuteNominativoList()
        + init()
        + isAppuntamentoDisabled()
        + isDeleteNominativoButtonRendered()
        + isDisabledButtonContestaNominativo()
        + isDisabledButtonDeleteNominativo()
        + isDisabledButtonMail()
        + isDisabledButtonPdf()
        + isDisabledButtonSimulator()
        + isDisabledButtonSms()
        + isDisabledFornitoreLead()
        + isDisabledProvenienza()
        + isPrintPdfDisabled()
        + isRenderedClock()
        + isRenderedDataCaricamento()
        + isRenderedEsitoSmsNotificaLead()
        + isRenderedLogPanel()
        + isRequiredFornitoreLead()
        + printPdfNominativo()
        + remove()
        + removeTratt()
        + resetContaNominativoDialog()
        + resetDataRecall()
        + resetSendDialog()
        + saveNominativo()
        + saveNominativo()
        + sendContestaNominativo()
        + sendEmail()
        + sendSms()
        + setAmministrazioneService()
        + setAmministrazioneViewModelList()
        + setArchiviazioneRendered()
        + setAziendaService()
        + setCfGenerator()
        + setClienteUtil()
        + setCommentoLog()
        + setContestaNominativoCommento()
        + setErrorConverter()
        + setExceptionResolverUtil()
        + setHttpSessionUtil()
        + setImpegniSelezionati()
        + setLaceMailSender()
        + setLogService()
        + setMailClient()
        + setMotivoContestazione()
        + setNominativo()
        + setNominativoService()
        + setNotificaLeadSmsViewModel()
        + setOperatorService()
        + setParameterAppuntamento()
        + setPassaggioParametriUtils()
        + setPreventiviDaCreare()
        + setPreventivoDaCreare()
        + setPreventivoList()
        + setPropertiesUtil()
        + setRequestTenantIdentifierResolver()
        + setResidenzaViewModel()
        + setSettingService()
        + setSimulatorUtilsView()
        + setSmsServiceFacade()
        + setSmsText()
        + setTrattenuteNominativoList()
        + viewAmministrazioneAssegnata()
        + viewAmministrazioneSelezionata()
        - clearPassaggioParametriCheckNominativo()
        - logContestazioneAccettata()
        - logContestazioneRifiutata()
        - logInvioContestazione()
        - saveClienteNominativoIdIntoPassaggioParametri()
        - setNominativoFromCheckNominativo()
        - setNominativoSelectedOnSearch()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.nominativo {
    class com.woonders.lacemsjsf.view.nominativo.ScheduleView {
        - event : ScheduleEvent
        - eventModel : ScheduleModel
        + addEvent()
        + getEvent()
        + getEventModel()
        + init()
        + onDateSelect()
        + onEventMove()
        + onEventResize()
        + onEventSelect()
        + setEvent()
        + setEventModel()
    }
  }
  

  com.woonders.lacemsjsf.view.nominativo.CheckNominativo .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.nominativo.CheckNominativo o-- com.woonders.lacemscommon.util.CfGenerator : cfGenerator
  com.woonders.lacemsjsf.view.nominativo.CheckNominativo o-- com.woonders.lacemscommon.service.CheckNominativoService : checkNominativoService
  com.woonders.lacemsjsf.view.nominativo.CheckNominativo o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.nominativo.CheckNominativo o-- com.woonders.lacemsjsf.config.PropertiesUtil : propertiesUtil
  com.woonders.lacemsjsf.view.nominativo.CheckNominativo o-- com.woonders.lacemscommon.db.entity.Cliente.Sesso : sesso
  com.woonders.lacemsjsf.view.nominativo.DashboardNominativo .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.nominativo.DashboardNominativo o-- com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView : aziendaSelectionView
  com.woonders.lacemsjsf.view.nominativo.DashboardNominativo o-- com.woonders.lacemscommon.service.AziendaService : aziendaService
  com.woonders.lacemsjsf.view.nominativo.DashboardNominativo o-- com.woonders.lacemscommon.service.DashboardNominativoService : dashboardNominativoService
  com.woonders.lacemsjsf.view.nominativo.DashboardNominativo o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.nominativo.DashboardNominativo o-- com.woonders.lacemscommon.service.NominativoService : nominativoService
  com.woonders.lacemsjsf.view.nominativo.DashboardNominativo o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.nominativo.DashboardNominativo o-- com.woonders.lacemscommon.app.viewmodel.ClienteViewModel : selectedNominativo
  com.woonders.lacemsjsf.view.nominativo.DatatableCheckNominativo .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.nominativo.DatatableCheckNominativo o-- com.woonders.lacemscommon.service.CheckNominativoService : checkNominativoService
  com.woonders.lacemsjsf.view.nominativo.DatatableCheckNominativo o-- com.woonders.lacemsjsf.util.CheckPermissionUtils : checkPermissionUtils
  com.woonders.lacemsjsf.view.nominativo.DatatableCheckNominativo o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.nominativo.DatatableCheckNominativo o-- com.woonders.lacemscommon.service.NominativoService : nominativoService
  com.woonders.lacemsjsf.view.nominativo.DatatableCheckNominativo o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.nominativo.DatatableCheckNominativo o-- com.woonders.lacemsjsf.config.PropertiesUtil : propertiesUtil
  com.woonders.lacemsjsf.view.nominativo.DatatableCheckNominativo o-- com.woonders.lacemscommon.app.viewmodel.ClienteViewModel : selectedNominativoViewModel
  com.woonders.lacemsjsf.view.nominativo.DatatableCheckNominativo o-- com.woonders.lacemscommon.db.entity.Cliente.Sesso : sesso
  com.woonders.lacemsjsf.view.nominativo.DatatableNominativiOmessiView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.nominativo.DatatableNominativiOmessiView o-- com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView : aziendaSelectionView
  com.woonders.lacemsjsf.view.nominativo.DatatableNominativiOmessiView o-- com.woonders.lacemscommon.service.DashboardNominativoService : dashboardNominativoService
  com.woonders.lacemsjsf.view.nominativo.DatatableNominativiOmessiView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.nominativo.DatatableNominativiOmessiView o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.nominativo.DatatableNominativiOmessiView o-- com.woonders.lacemscommon.app.viewmodel.ClienteViewModel : selectedNominativoViewModel
  com.woonders.lacemsjsf.view.nominativo.DatatableNominativoRinnoviView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.nominativo.DatatableNominativoRinnoviView o-- com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView : aziendaSelectionView
  com.woonders.lacemsjsf.view.nominativo.DatatableNominativoRinnoviView o-- com.woonders.lacemscommon.service.AziendaService : aziendaService
  com.woonders.lacemsjsf.view.nominativo.DatatableNominativoRinnoviView o-- com.woonders.lacemscommon.service.DashboardNominativoService : dashboardNominativoService
  com.woonders.lacemsjsf.view.nominativo.DatatableNominativoRinnoviView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.nominativo.DatatableNominativoRinnoviView o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.nominativo.DatatableNominativoRinnoviView o-- com.woonders.lacemscommon.app.model.ClienteTrattenuta : selectedClienteTrattenuta
  com.woonders.lacemsjsf.view.nominativo.NominativoPdfView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.nominativo.NominativoPdfView o-- com.woonders.lacemsjsf.view.pdf.NominativoPdf : nominativoPdf
  com.woonders.lacemsjsf.view.nominativo.NominativoPdfView o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.nominativo.NominativoPdfView o-- com.woonders.lacemsjsf.view.pdf.StreamPdf : stream
  com.woonders.lacemsjsf.view.nominativo.Register .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemscommon.service.AmministrazioneService : amministrazioneService
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemsjsf.view.file.ArchiviazioneRendered : archiviazioneRendered
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemscommon.service.AziendaService : aziendaService
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemscommon.util.CfGenerator : cfGenerator
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemscommon.db.entityutil.ClienteUtil : clienteUtil
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemsjsf.util.ErrorConverter : errorConverter
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemsjsf.util.ExceptionResolverUtil : exceptionResolverUtil
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemscommon.util.LaceMailSender : laceMailSender
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemscommon.service.LogService : logService
  com.woonders.lacemsjsf.view.nominativo.Register o-- mail.MailClient : mailClient
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemscommon.app.viewmodel.ClienteViewModel : nominativo
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemscommon.service.NominativoService : nominativoService
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemscommon.app.viewmodel.NotificaLeadSmsViewModel : notificaLeadSmsViewModel
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemscommon.service.OperatorService : operatorService
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemscommon.app.viewmodel.PraticaViewModel : preventivoDaCreare
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemsjsf.config.PropertiesUtil : propertiesUtil
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemsjsf.db.app.config.RequestTenantIdentifierResolver : requestTenantIdentifierResolver
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemscommon.app.viewmodel.ResidenzaViewModel : residenzaViewModel
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemscommon.service.SettingService : settingService
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemsjsf.view.simulator.SimulatorUtilsView : simulatorUtilsView
  com.woonders.lacemsjsf.view.nominativo.Register o-- com.woonders.lacemscommon.service.SmsServiceFacade : smsServiceFacade
  com.woonders.lacemsjsf.view.nominativo.ScheduleView .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
