@startuml

title __BEANCONFIG's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace config {
      namespace beanconfig {
        class com.woonders.lacemscommon.config.beanconfig.BaseCondition {
            + isProduction()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace config {
      namespace beanconfig {
        class com.woonders.lacemscommon.config.beanconfig.MockCondition {
            + matches()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace config {
      namespace beanconfig {
        class com.woonders.lacemscommon.config.beanconfig.ProductionBeanConfiguration {
            + mockSmsClient()
            + smsClient()
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace config {
      namespace beanconfig {
        class com.woonders.lacemscommon.config.beanconfig.ProductionCondition {
            + matches()
        }
      }
    }
  }
  

  com.woonders.lacemscommon.config.beanconfig.MockCondition .up.|> org.springframework.context.annotation.Condition
  com.woonders.lacemscommon.config.beanconfig.MockCondition -up-|> com.woonders.lacemscommon.config.beanconfig.BaseCondition
  com.woonders.lacemscommon.config.beanconfig.ProductionCondition .up.|> org.springframework.context.annotation.Condition
  com.woonders.lacemscommon.config.beanconfig.ProductionCondition -up-|> com.woonders.lacemscommon.config.beanconfig.BaseCondition


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
