@startuml

title __NEWDOC's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.response {
        namespace newdoc {
          class com.woonders.lacemscommon.fattureincloud.network.response.newdoc.NewDocResponse {
              - newId : String
              - token : String
              + NewDocResponse()
              + NewDocResponse()
              {static} + builder()
              + getNewId()
              + getToken()
              + setNewId()
              + setToken()
              + toString()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace fattureincloud {
      namespace network.response {
        namespace newdoc {
          class com.woonders.lacemscommon.fattureincloud.network.response.newdoc.NewDocResponse.NewDocResponseBuilder {
              - newId : String
              - token : String
              + build()
              + newId()
              + toString()
              + token()
              ~ NewDocResponseBuilder()
          }
        }
      }
    }
  }
  

  com.woonders.lacemscommon.fattureincloud.network.response.newdoc.NewDocResponse -up-|> com.woonders.lacemscommon.fattureincloud.network.response.BaseResponse
  com.woonders.lacemscommon.fattureincloud.network.response.newdoc.NewDocResponse +-down- com.woonders.lacemscommon.fattureincloud.network.response.newdoc.NewDocResponse.NewDocResponseBuilder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
