@startuml

title __BACKUPEXCEL's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace app.backupexcel {
      class com.woonders.lacemscommon.app.backupexcel.ExcelWriterComponent {
          {static} + JSF_NAME : String
          {static} + NAME : String
          {static} - CF : String
          {static} - CODICEPRATICA : String
          {static} - COGNOME : String
          {static} - COUNT_PASSWORD_SIZE : int
          {static} - NOME : String
          {static} - OPERATORE : String
          {static} - PAGE_SIZE : int
          {static} - VIEWID : String
          + startBackupFile()
          - chooseValueToWriteOnCell()
          - chooseValueToWriteOnCellAmministrazioni()
          - chooseValueToWriteOnCellNominativi()
          - chooseValueToWriteOnCellValutazioniAmministrazioni()
          - createSheet()
          - createWorkbook()
          - getAmministrazioneFields()
          - getClienteFields()
          - getContoFields()
          - getDocumentoFields()
          - getEstinzioneFields()
          - getPraticaFields()
          - getResidenzaFields()
          - getTrattenuteFields()
          - getValutazioneAmministrazioneFields()
          - writeAmministrazioni()
          - writeClienti()
          - writeEstinzioniPratiche()
          - writeFirstRowAmministrazioni()
          - writeFirstRowClienti()
          - writeFirstRowEstinzionePratiche()
          - writeFirstRowNominativi()
          - writeFirstRowNominativiImpegni()
          - writeFirstRowPraticheCliente()
          - writeFirstRowTrattenuteCliente()
          - writeFirstRowValutazioneAmministrazioni()
          - writeNominativi()
          - writeNominativi()
          - writeOnCellAmministrazioni()
          - writeOnCellClienteByType()
          - writeOnCellClienti()
          - writeOnCellEstinzionePratiche()
          - writeOnCellNominativi()
          - writeOnCellNominativiImpegni()
          - writeOnCellPraticheCliente()
          - writeOnCellTrattenuteCliente()
          - writeOnCellValutazioneAmministrazioni()
          - writePraticheCliente()
          - writeTrattenuteCliente()
      }
    }
  }
  

  com.woonders.lacemscommon.app.backupexcel.ExcelWriterComponent o-- com.woonders.lacemscommon.service.BackupService : backupService
  com.woonders.lacemscommon.app.backupexcel.ExcelWriterComponent o-- com.woonders.lacemscommon.util.LaceMailSender : laceMailSender


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
