@startuml

title __FORMCLIENTE's Class Diagram__\n

  namespace com.woonders.lacemsjsf.view.formcliente {
    class com.woonders.lacemsjsf.view.formcliente.CheckCf {
        {static} + JSF_NAME : String
        {static} + NAME : String
        - codiceF : String
        - cognome : String
        - dataNascita : Date
        - luogoNascita : String
        - nome : String
        - tipoPratica : String
        + calcCF()
        + getCfGenerator()
        + getClienteManagerService()
        + getCodiceF()
        + getCognome()
        + getDataNascita()
        + getDateConversionUtil()
        + getLuogoNascita()
        + getNome()
        + getPassaggioParametriUtils()
        + getPropertiesUtil()
        + getSesso()
        + getTipoPratica()
        + newClient()
        + setCfGenerator()
        + setClienteManagerService()
        + setCodiceF()
        + setCognome()
        + setDataNascita()
        + setDateConversionUtil()
        + setLuogoNascita()
        + setNome()
        + setPassaggioParametriUtils()
        + setPropertiesUtil()
        + setSesso()
        + setTipoPratica()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.formcliente {
    class com.woonders.lacemsjsf.view.formcliente.FormClientePdfView {
        {static} + JSF_NAME : String
        {static} + NAME : String
        - file : ByteArrayOutputStream
        {static} - logger : Logger
        + FormClientePdfView()
        + getAllegatiPdf()
        + getAnagraficaPdf()
        + getAziendaService()
        + getClienteManagerService()
        + getFile()
        + getIdFile()
        + getPassaggioParametriUtils()
        + getPrefinPdf()
        + getPrivacyPdf()
        + getStream()
        + setAllegatiPdf()
        + setAnagraficaPdf()
        + setAziendaService()
        + setClienteManagerService()
        + setFile()
        + setPassaggioParametriUtils()
        + setPrefinPdf()
        + setPrivacyPdf()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.formcliente {
    class com.woonders.lacemsjsf.view.formcliente.RegisterCliente {
        {static} + JSF_NAME : String
        {static} + NAME : String
        - PRATICA_RINNOVATA : String
        - RESIDENZA_PRECEDENTE : int
        - amministrazioneViewModelList : List<AmministrazioneViewModel>
        - coesistenzeEstinguibiliViewModelList : List<TrattenuteViewModel>
        - coesistenzeSelezionateDaEstinguereViewModelList : List<TrattenuteViewModel>
        - commentoLog : String
        - coobbligatoViewModelList : List<CoobbligatoViewModel>
        - estinzioneViewModelList : List<EstinzioneViewModel>
        - file : ByteArrayOutputStream
        - finanziariaViewModelList : List<FinanziariaViewModel>
        {static} - log : Logger
        - praticheEstinguibiliViewModelList : List<PraticaViewModel>
        - praticheInCorsoViewModelList : List<PraticheInCorsoModel>
        - praticheSelezionateDaEstinguereViewModelList : List<PraticaViewModel>
        - preventivoViewModelList : List<PreventivoViewModel>
        - smsText : String
        - trattenuteViewModelList : List<TrattenuteViewModel>
        + RegisterCliente()
        + addCoobbligato()
        + addEstinzione()
        + addPreventiviToBody()
        + addPreventiviToBodySMS()
        + addPreventivo()
        + addPreventivoFromSimulatorResultRowChoosen()
        + addRichiestaBustaToBody()
        + addRichiestaBustaToBodySMS()
        + addSecondaOccupazione()
        + addTrattenuta()
        + calcReverseCf()
        + canWriteCliente()
        + checkDoc()
        + checkIban()
        + clearPassaggioParametriAmministrazione()
        + completeAmministrazione()
        + creaPraticaDaPreventivo()
        + disabledField()
        + getAmministrazioneAssegnata()
        + getAmministrazioneSelezionata()
        + getAmministrazioneService()
        + getAmministrazioneViewModelList()
        + getArchiviazioneRendered()
        + getAziendaService()
        + getAziendaViewModel()
        + getCalculationUtils()
        + getCfGenerator()
        + getClienteManagerService()
        + getClienteUtil()
        + getClienteViewModel()
        + getCoesistenzeEstinguibiliViewModelList()
        + getCoesistenzeSelezionateDaEstinguereViewModelList()
        + getCommentoLog()
        + getConstantResolverView()
        + getContoViewModel()
        + getCoobbligatoService()
        + getCoobbligatoViewModel()
        + getCoobbligatoViewModelList()
        + getDisabledRendered()
        + getDocumentoViewModel()
        + getErrorConverter()
        + getEstinzioneUtil()
        + getEstinzioneViewModelList()
        + getExceptionResolverUtil()
        + getFile()
        + getFinanziariaService()
        + getFinanziariaViewModelList()
        + getHttpSessionUtil()
        + getLaceMailSender()
        + getLogService()
        + getMailClient()
        + getOperatorService()
        + getPRATICA_RINNOVATA()
        + getPassaggioParametriUtils()
        + getPraticaRendered()
        + getPraticaUtil()
        + getPraticaViewModel()
        + getPraticheEstinguibiliViewModelList()
        + getPraticheInCorsoService()
        + getPraticheInCorsoViewModel()
        + getPraticheInCorsoViewModelList()
        + getPraticheSelezionateDaEstinguereViewModelList()
        + getPreferenzaStatoPraticaService()
        + getPreventivoDaCreareViewModel()
        + getPreventivoService()
        + getPreventivoUtil()
        + getPreventivoViewModel()
        + getPreventivoViewModelList()
        + getPropertiesUtil()
        + getRESIDENZA_PRECEDENTE()
        + getRequestTenantIdentifierResolver()
        + getResidenzaUtil()
        + getResidenzaViewModel()
        + getSettingService()
        + getSimulatorUtilsView()
        + getSmsServiceFacade()
        + getSmsText()
        + getTrattenuteViewModel()
        + getTrattenuteViewModelList()
        + init()
        + isAddCoobbligatoDisabled()
        + isAppuntamentoDisabled()
        + isDataPerfezionamentoDisabled()
        + isDisabledAddPreventivo()
        + isDisabledAddPreventivoDaSimulatore()
        + isDisabledButtonAllegati()
        + isDisabledButtonContestaNominativo()
        + isDisabledButtonMail()
        + isDisabledButtonPdf()
        + isDisabledButtonSms()
        + isDisabledFornitoreLead()
        + isDisabledProvenienza()
        + isDomicilioAltroDisabled()
        + isMenoQuattroAnni()
        + isPrintPdfDisabled()
        + isProvvigioneEuroDisabled()
        + isProvvigionePercentualeDisabled()
        + isRenderedLogPanel()
        + praticaRinnovataOnBigTopic()
        + printPdf()
        + provConfirm()
        + removeCoobbligato()
        + removePreventivo()
        + removeSecondaOccupazione()
        + removeTrattenuta()
        + renderedPrestito()
        + resetDataRecall()
        + resetSendDialog()
        + retrieveAllCoesistenzeCliente()
        + retrieveAllPraticheCliente()
        + saveNewCliente()
        + sendEmail()
        + sendSms()
        + setAmministrazioneSelezionata()
        + setAmministrazioneService()
        + setAmministrazioneViewModelList()
        + setArchiviazioneRendered()
        + setAziendaService()
        + setAziendaViewModel()
        + setCalculationUtils()
        + setCfGenerator()
        + setClienteManagerService()
        + setClienteNuovaPratica()
        + setClienteUtil()
        + setClienteViewModel()
        + setCoesistenzeEstinguibiliViewModelList()
        + setCoesistenzeSelezionateDaEstinguereViewModelList()
        + setCommentoLog()
        + setConstantResolverView()
        + setContoViewModel()
        + setCoobbligatoService()
        + setCoobbligatoViewModel()
        + setCoobbligatoViewModelList()
        + setDataNotificaStatoPratica()
        + setDocumentoViewModel()
        + setErrorConverter()
        + setEstinzioneUtil()
        + setEstinzioneViewModelList()
        + setExceptionResolverUtil()
        + setFile()
        + setFinanziariaService()
        + setFinanziariaViewModelList()
        + setHttpSessionUtil()
        + setLaceMailSender()
        + setLogService()
        + setMailClient()
        + setNewDateByStatoPratica()
        + setOperatorService()
        + setParameterAppuntamento()
        + setPassaggioParametriUtils()
        + setPraticaRendered()
        + setPraticaUtil()
        + setPraticaViewModel()
        + setPraticheEstinguibiliViewModelList()
        + setPraticheInCorsoService()
        + setPraticheInCorsoViewModel()
        + setPraticheInCorsoViewModelList()
        + setPraticheSelezionateDaEstinguereViewModelList()
        + setPreferenzaStatoPraticaService()
        + setPreventivoDaCreare()
        + setPreventivoDaCreareViewModel()
        + setPreventivoService()
        + setPreventivoUtil()
        + setPreventivoViewModel()
        + setPreventivoViewModelList()
        + setPropertiesUtil()
        + setRequestTenantIdentifierResolver()
        + setResidenzaUtil()
        + setResidenzaViewModel()
        + setSettingService()
        + setSimulatorUtilsView()
        + setSmsServiceFacade()
        + setSmsText()
        + setTrattenuteViewModelList()
        + viewAmministrazioneSelezionata()
        + viewAmministrazioniAssegnate()
        + viewCoobbligato()
        + viewPraticheInCorso()
        - checkLimitEstinzioniSelezionate()
        - saveClientePraticaIdIntoPassaggioParametri()
        - setClienteSelectedOnSearch()
        - updateAllViewModels()
    }
  }
  

  com.woonders.lacemsjsf.view.formcliente.CheckCf .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.formcliente.CheckCf o-- com.woonders.lacemscommon.util.CfGenerator : cfGenerator
  com.woonders.lacemsjsf.view.formcliente.CheckCf o-- com.woonders.lacemscommon.service.ClienteManagerService : clienteManagerService
  com.woonders.lacemsjsf.view.formcliente.CheckCf o-- com.woonders.lacemscommon.util.DateConversionUtil : dateConversionUtil
  com.woonders.lacemsjsf.view.formcliente.CheckCf o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.formcliente.CheckCf o-- com.woonders.lacemsjsf.config.PropertiesUtil : propertiesUtil
  com.woonders.lacemsjsf.view.formcliente.CheckCf o-- com.woonders.lacemscommon.db.entity.Cliente.Sesso : sesso
  com.woonders.lacemsjsf.view.formcliente.FormClientePdfView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.formcliente.FormClientePdfView o-- com.woonders.lacemsjsf.view.pdf.AllegatiPdf : allegatiPdf
  com.woonders.lacemsjsf.view.formcliente.FormClientePdfView o-- com.woonders.lacemsjsf.view.pdf.AnagraficaPdf : anagraficaPdf
  com.woonders.lacemsjsf.view.formcliente.FormClientePdfView o-- com.woonders.lacemscommon.service.AziendaService : aziendaService
  com.woonders.lacemsjsf.view.formcliente.FormClientePdfView o-- com.woonders.lacemscommon.service.ClienteManagerService : clienteManagerService
  com.woonders.lacemsjsf.view.formcliente.FormClientePdfView o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.formcliente.FormClientePdfView o-- com.woonders.lacemsjsf.view.pdf.PrefinPdf : prefinPdf
  com.woonders.lacemsjsf.view.formcliente.FormClientePdfView o-- com.woonders.lacemsjsf.view.pdf.PrivacyPdf : privacyPdf
  com.woonders.lacemsjsf.view.formcliente.FormClientePdfView o-- com.woonders.lacemsjsf.view.pdf.StreamPdf : stream
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.app.viewmodel.AmministrazioneViewModel : amministrazioneSelezionata
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.service.AmministrazioneService : amministrazioneService
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemsjsf.view.file.ArchiviazioneRendered : archiviazioneRendered
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.service.AziendaService : aziendaService
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.app.viewmodel.AziendaViewModel : aziendaViewModel
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemsjsf.util.CalculationUtils : calculationUtils
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.util.CfGenerator : cfGenerator
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.service.ClienteManagerService : clienteManagerService
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.db.entityutil.ClienteUtil : clienteUtil
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.app.viewmodel.ClienteViewModel : clienteViewModel
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemsjsf.view.util.ConstantResolverView : constantResolverView
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.app.viewmodel.ContoViewModel : contoViewModel
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.service.CoobbligatoService : coobbligatoService
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.app.viewmodel.CoobbligatoViewModel : coobbligatoViewModel
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- data.DisabledRendered : disabledRendered
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.app.viewmodel.DocumentoViewModel : documentoViewModel
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemsjsf.util.ErrorConverter : errorConverter
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.db.entityutil.EstinzioneUtil : estinzioneUtil
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemsjsf.util.ExceptionResolverUtil : exceptionResolverUtil
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.service.FinanziariaService : finanziariaService
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.util.LaceMailSender : laceMailSender
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.service.LogService : logService
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- mail.MailClient : mailClient
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.service.OperatorService : operatorService
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemsjsf.view.prestiti.PraticaRendered : praticaRendered
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.db.entityutil.PraticaUtil : praticaUtil
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.app.viewmodel.PraticaViewModel : praticaViewModel
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.service.PraticheInCorsoService : praticheInCorsoService
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.app.model.PraticheInCorsoModel : praticheInCorsoViewModel
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.service.PreferenzaStatoPraticaService : preferenzaStatoPraticaService
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.app.viewmodel.PreventivoViewModel : preventivoDaCreareViewModel
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.service.PreventivoService : preventivoService
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.db.entityutil.PreventivoUtil : preventivoUtil
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.app.viewmodel.PreventivoViewModel : preventivoViewModel
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemsjsf.config.PropertiesUtil : propertiesUtil
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemsjsf.db.app.config.RequestTenantIdentifierResolver : requestTenantIdentifierResolver
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.db.entityutil.ResidenzaUtil : residenzaUtil
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.app.viewmodel.ResidenzaViewModel : residenzaViewModel
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.service.SettingService : settingService
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemsjsf.view.simulator.SimulatorUtilsView : simulatorUtilsView
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.service.SmsServiceFacade : smsServiceFacade
  com.woonders.lacemsjsf.view.formcliente.RegisterCliente o-- com.woonders.lacemscommon.app.viewmodel.TrattenuteViewModel : trattenuteViewModel


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
