@startuml

title __BACKUP's Class Diagram__\n

  namespace com.woonders.lacemsjsf.view.backup {
    class com.woonders.lacemsjsf.view.backup.BackupView {
        {static} + JSF_NAME : String
        {static} + NAME : String
        {static} - BACKUP_EXPIRATION_INTERVAL_DAYS : long
        {static} - DO_BACKUP_INTERVAL_DAYS : long
        {static} - FILENAME : String
        {static} - LACE : String
        - backupFile : byte[]
        - dateLastBackup : LocalDateTime
        - emailOperator : String
        - password : String
        + actionBackup()
        + downloadBackupFile()
        + getBackupFile()
        + getBackupService()
        + getDateLastBackup()
        + getEmailOperator()
        + getExcelWriterComponent()
        + getHttpSessionUtil()
        + getOperatorService()
        + getPassword()
        + getPropertiesUtil()
        + getRequestTenantIdentifierResolver()
        + init()
        + isDisabledActionBackupButton()
        + isDownloadBackupButtonDisabled()
        + setBackupFile()
        + setBackupService()
        + setDateLastBackup()
        + setEmailOperator()
        + setExcelWriterComponent()
        + setHttpSessionUtil()
        + setOperatorService()
        + setPassword()
        + setPropertiesUtil()
        + setRequestTenantIdentifierResolver()
        - generateDefaultStreamedContentWithBackupFile()
    }
  }
  

  com.woonders.lacemsjsf.view.backup.BackupView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.backup.BackupView o-- com.woonders.lacemscommon.service.BackupService : backupService
  com.woonders.lacemsjsf.view.backup.BackupView o-- com.woonders.lacemscommon.app.backupexcel.ExcelWriterComponent : excelWriterComponent
  com.woonders.lacemsjsf.view.backup.BackupView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.backup.BackupView o-- com.woonders.lacemscommon.service.OperatorService : operatorService
  com.woonders.lacemsjsf.view.backup.BackupView o-- com.woonders.lacemsjsf.config.PropertiesUtil : propertiesUtil
  com.woonders.lacemsjsf.view.backup.BackupView o-- com.woonders.lacemsjsf.db.app.config.RequestTenantIdentifierResolver : requestTenantIdentifierResolver


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
