@startuml

title __ITALCREDI's Class Diagram__\n

  namespace enumPdf {
    namespace italcredi {
      enum PagesAllegatiA {
        ALLEGATO_A
        ALLEGATO_A1
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace italcredi {
      enum PagesAllegatiB {
        ALLEGATO_B
        ALLEGATO_B1
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace italcredi {
      enum PagesAllegatiCertificati {
        CERTIFICATO_STIPENDIO
        DELEGA_RICHIESTA_CERTIFICATI
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace italcredi {
      enum PagesAllegatiE {
        ALLEGATO_E_PAG1
        ALLEGATO_E_PAG2
        ALLEGATO_E_PAG3
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace italcredi {
      enum PagesAllegatiNetB {
        CREDITO_NET_ALL_B
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace italcredi {
      enum PagesCreditoNetC {
        CREDITO_NET_C
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace italcredi {
      enum PagesDelegaAllegatoB {
        DELEGA_ALLEGATO_B
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace italcredi {
      enum PagesDelegaCreditoNet {
        DELEGA_CREDITO_NET
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace italcredi {
      enum PagesPrefin {
        MOD_AM1542_PAG1
        MOD_AM1542_PAG2
        MOD_CQ2252_PAG1
        MOD_CQ2252_PAG2
        MOD_FI1596_PAG1
        MOD_FI1596_PAG2
        MOD_FI1596_PAG3
        MOD_FI1596_PAG4
        MOD_NORME_1103_PAG1
        MOD_NORME_1103_PAG2
        MOD_NORME_1104_PAG1
        MOD_NORME_1104_PAG2
        PAGINA_VUOTA_AM1542_1
        PAGINA_VUOTA_AM1542_2
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace italcredi {
      enum PagesPrefinConteggio {
        PAGINA_VUOTA_CONTEGGIO_1
        RICHIESTA_CONTEGGIO_1
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace italcredi {
      enum PagesPrefinConteggio2 {
        PAGINA_VUOTA_CONTEGGIO_2
        RICHIESTA_CONTEGGIO_2
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace italcredi {
      enum PagesPrefinEstratti {
        PAGINA_VUOTA_ESTRATTI_1
        PAGINA_VUOTA_ESTRATTI_2
        PAGINA_VUOTA_ESTRATTI_3
        RICHIESTA_ESTRATTI_PAG1
        RICHIESTA_ESTRATTI_PAG2
        RICHIESTA_ESTRATTI_PAG3
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace italcredi {
      enum PagesPrefinTfr {
        AUTOCERTIFICA_TFR
        PAGINA_VUOTA_TFR
        page
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
