@startuml

title __VIEW's Class Diagram__\n

  namespace org.primefaces.ultima.view {
    class org.primefaces.ultima.view.AutoCompleteView {
        - selectedThemes : List<Theme>
        - txt1 : String
        - txt2 : String
        - txt3 : String
        - txt4 : String
        - txt5 : String
        - txt6 : String
        - txt7 : String
        - txt8 : String
        + completeText()
        + completeTheme()
        + completeThemeContains()
        + getSelectedThemes()
        + getTheme1()
        + getTheme2()
        + getTheme3()
        + getTheme4()
        + getThemeGroup()
        + getTxt1()
        + getTxt2()
        + getTxt3()
        + getTxt4()
        + getTxt5()
        + getTxt6()
        + getTxt7()
        + getTxt8()
        + onItemSelect()
        + setSelectedThemes()
        + setService()
        + setTheme1()
        + setTheme2()
        + setTheme3()
        + setTheme4()
        + setTxt1()
        + setTxt2()
        + setTxt3()
        + setTxt4()
        + setTxt5()
        + setTxt6()
        + setTxt7()
        + setTxt8()
    }
  }
  

  namespace org.primefaces.ultima.view {
    class org.primefaces.ultima.view.GuestPreferences {
        - compact : boolean
        - menuClass : String
        - menuLayout : String
        - orientationRTL : boolean
        - profileMode : String
        - theme : String
        - themeColors : Map<String, String>
        + getMenuClass()
        + getMenuLayout()
        + getProfileMode()
        + getTheme()
        + getThemeColors()
        + init()
        + isCompact()
        + isOrientationRTL()
        + setCompact()
        + setDarkMenu()
        + setLightMenu()
        + setMenuLayout()
        + setOrientationRTL()
        + setProfileMode()
        + setTheme()
    }
  }
  

  org.primefaces.ultima.view.AutoCompleteView .up.|> java.io.Serializable
  org.primefaces.ultima.view.AutoCompleteView o-- org.primefaces.ultima.service.ThemeService : service
  org.primefaces.ultima.view.AutoCompleteView o-- org.primefaces.ultima.domain.Theme : theme1
  org.primefaces.ultima.view.AutoCompleteView o-- org.primefaces.ultima.domain.Theme : theme2
  org.primefaces.ultima.view.AutoCompleteView o-- org.primefaces.ultima.domain.Theme : theme3
  org.primefaces.ultima.view.AutoCompleteView o-- org.primefaces.ultima.domain.Theme : theme4
  org.primefaces.ultima.view.GuestPreferences .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
