@startuml

title __DASHBOARD's Class Diagram__\n

  namespace com.woonders.lacemsjsf.view.dashboard {
    class com.woonders.lacemsjsf.view.dashboard.DashboardNotificationView {
        {static} - log : Logger
        - sumSmsBalanceAziende : Integer
        + balanceSmsMarketingOperatore()
        + balanceSmsNotificaLead()
        + findClienteToRecall()
        + findCoesistenzaRinnovabile()
        + findPraticaRinnovabile()
        + findPreventivo()
        + getAziendaSelectionView()
        + getAziendaService()
        + getDashboardNominativoService()
        + getDashboardService()
        + getHttpSessionUtil()
        + getOperatorService()
        + getPassaggioParametriUtils()
        + getSettingService()
        + getStatoNominativoService()
        + getSumSmsBalanceAziende()
        + impegniRinnovabiliSize()
        + newLeadSize()
        + nominativiDaLavorareSize()
        + nominativiOmessiSize()
        + nominativiRecallSize()
        + numberRecall()
        + numberRinnovoCoesistenza()
        + numberRinnovoPratica()
        + preventiviInCorsoSize()
        + setAziendaSelectionView()
        + setAziendaService()
        + setDashboardNominativoService()
        + setDashboardService()
        + setHttpSessionUtil()
        + setOperatorService()
        + setPassaggioParametriUtils()
        + setSettingService()
        + setStatoNominativoService()
        + setSumSmsBalanceAziende()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.dashboard {
    class com.woonders.lacemsjsf.view.dashboard.DashboardStatisticView {
        + getAziendaSelectionView()
        + getAziendaService()
        + getDashboardService()
        + getHttpSessionUtil()
        + getSettingService()
        + init()
        + numeroPraticheCaricate()
        + numeroPratichePerfezionate()
        + setAziendaSelectionView()
        + setAziendaService()
        + setDashboardService()
        + setHttpSessionUtil()
        + setSettingService()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.dashboard {
    class com.woonders.lacemsjsf.view.dashboard.DatatableDashboardNotificationPreventivoView {
        - clientiPreventiviList : LazyDataModel<ClientePreventivo>
        + getAziendaSelectionView()
        + getClientiPreventiviList()
        + getDashboardService()
        + getHttpSessionUtil()
        + getPassaggioParametriUtils()
        + getSelectedClientePreventivo()
        + init()
        + onRowSelect()
        + setAziendaSelectionView()
        + setClientiPreventiviList()
        + setDashboardService()
        + setHttpSessionUtil()
        + setNotificationPreventivo()
        + setPassaggioParametriUtils()
        + setSelectedClientePreventivo()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.dashboard {
    class com.woonders.lacemsjsf.view.dashboard.DatatableDashboardNotificationView {
        {static} - DA_RICHIAMARE : String
        {static} - RINNOVO_COESISTENZE : String
        {static} - RINNOVO_PRATICA : String
        - clientiListLazy : LazyDataModel<ClientePratica>
        - renderedRecallColumn : boolean
        - renderedRinnovoCoesistenzaColumn : boolean
        - renderedRinnovoPraticaColumn : boolean
        - tableTitle : String
        + getAziendaSelectionView()
        + getAziendaService()
        + getClientiListLazy()
        + getDashboardService()
        + getHttpSessionUtil()
        + getPassaggioParametriUtils()
        + getSelectedCliente()
        + getTableTitle()
        + init()
        + isRenderedRecallColumn()
        + isRenderedRinnovoCoesistenzaColumn()
        + isRenderedRinnovoPraticaColumn()
        + onRowSelect()
        + setAziendaSelectionView()
        + setAziendaService()
        + setClientiListLazy()
        + setDashboardService()
        + setHttpSessionUtil()
        + setNotification()
        + setPassaggioParametriUtils()
        + setRenderedRecallColumn()
        + setRenderedRinnovoCoesistenzaColumn()
        + setRenderedRinnovoPraticaColumn()
        + setSelectedCliente()
        + setTableTitle()
        - allClientiPratica()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.dashboard {
    class com.woonders.lacemsjsf.view.dashboard.DatatableDashboardView {
        - clientePraticaLazyDataModel : LazyDataModel<ClientePratica>
        + getAziendaSelectionView()
        + getClientePraticaLazyDataModel()
        + getDashboardService()
        + getHttpSessionUtil()
        + getPassaggioParametriUtils()
        + getSelectedCliente()
        + init()
        + onRowSelect()
        + setAziendaSelectionView()
        + setClientePraticaLazyDataModel()
        + setDashboardService()
        + setHttpSessionUtil()
        + setPassaggioParametriUtils()
        + setSelectedCliente()
    }
  }
  

  namespace com.woonders.lacemsjsf.view.dashboard {
    class com.woonders.lacemsjsf.view.dashboard.LineChartModelView {
        - lineModel : LineChartModel
        - monthsChartMap : Map<String, Date>
        + createLineModel()
        + getAziendaSelectionView()
        + getDashboardService()
        + getGraficoEnum()
        + getHttpSessionUtil()
        + getLineModel()
        + getMonthsChartMap()
        + init()
        + refreshChart()
        + setAziendaSelectionView()
        + setDashboardService()
        + setGraficoEnum()
        + setHttpSessionUtil()
        + setLineModel()
        + setMonthsChartMap()
        - generateMonthsChartMap()
        - generateOwnAgenziaMontanteChart()
        - generateOwnMontanteChart()
        - generateSelectedAgenziaOrAllMontanteChart()
        - initCategoryModel()
    }
  }
  

  com.woonders.lacemsjsf.view.dashboard.DashboardNotificationView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.dashboard.DashboardNotificationView o-- com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView : aziendaSelectionView
  com.woonders.lacemsjsf.view.dashboard.DashboardNotificationView o-- com.woonders.lacemscommon.service.AziendaService : aziendaService
  com.woonders.lacemsjsf.view.dashboard.DashboardNotificationView o-- com.woonders.lacemscommon.service.DashboardNominativoService : dashboardNominativoService
  com.woonders.lacemsjsf.view.dashboard.DashboardNotificationView o-- com.woonders.lacemscommon.service.DashboardService : dashboardService
  com.woonders.lacemsjsf.view.dashboard.DashboardNotificationView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.dashboard.DashboardNotificationView o-- com.woonders.lacemscommon.service.OperatorService : operatorService
  com.woonders.lacemsjsf.view.dashboard.DashboardNotificationView o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.dashboard.DashboardNotificationView o-- com.woonders.lacemscommon.service.SettingService : settingService
  com.woonders.lacemsjsf.view.dashboard.DashboardNotificationView o-- com.woonders.lacemscommon.service.StatoNominativoService : statoNominativoService
  com.woonders.lacemsjsf.view.dashboard.DashboardStatisticView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.dashboard.DashboardStatisticView o-- com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView : aziendaSelectionView
  com.woonders.lacemsjsf.view.dashboard.DashboardStatisticView o-- com.woonders.lacemscommon.service.AziendaService : aziendaService
  com.woonders.lacemsjsf.view.dashboard.DashboardStatisticView o-- com.woonders.lacemscommon.service.DashboardService : dashboardService
  com.woonders.lacemsjsf.view.dashboard.DashboardStatisticView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.dashboard.DashboardStatisticView o-- com.woonders.lacemscommon.service.SettingService : settingService
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardNotificationPreventivoView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardNotificationPreventivoView o-- com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView : aziendaSelectionView
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardNotificationPreventivoView o-- com.woonders.lacemscommon.service.DashboardService : dashboardService
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardNotificationPreventivoView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardNotificationPreventivoView o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardNotificationPreventivoView o-- com.woonders.lacemscommon.app.model.ClientePreventivo : selectedClientePreventivo
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardNotificationView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardNotificationView o-- com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView : aziendaSelectionView
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardNotificationView o-- com.woonders.lacemscommon.service.AziendaService : aziendaService
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardNotificationView o-- com.woonders.lacemscommon.service.DashboardService : dashboardService
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardNotificationView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardNotificationView o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardNotificationView o-- com.woonders.lacemscommon.app.model.ClientePratica : selectedCliente
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardView o-- com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView : aziendaSelectionView
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardView o-- com.woonders.lacemscommon.service.DashboardService : dashboardService
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardView o-- com.woonders.lacemsjsf.util.PassaggioParametriUtils : passaggioParametriUtils
  com.woonders.lacemsjsf.view.dashboard.DatatableDashboardView o-- com.woonders.lacemscommon.app.model.ClientePratica : selectedCliente
  com.woonders.lacemsjsf.view.dashboard.LineChartModelView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.dashboard.LineChartModelView o-- com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView : aziendaSelectionView
  com.woonders.lacemsjsf.view.dashboard.LineChartModelView o-- com.woonders.lacemscommon.service.DashboardService : dashboardService
  com.woonders.lacemsjsf.view.dashboard.LineChartModelView o-- com.woonders.lacemscommon.laceenum.GraficoEnum : graficoEnum
  com.woonders.lacemsjsf.view.dashboard.LineChartModelView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
