@startuml

title __AZIENDASELECTION's Class Diagram__\n

  namespace com.woonders.lacemsjsf.view.azienda {
    namespace election {
      class com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView {
          {static} + JSF_NAME : String
          {static} + NAME : String
          - aziendaCount : long
          - aziendaViewModelList : List<AziendaViewModel>
          {static} - log : Logger
          - operatorAziendaId : Long
          - selectedAziendaId : Long
          + getAziendaCount()
          + getAziendaService()
          + getAziendaViewModelList()
          + getCurrentAziendaId()
          + getCurrentMenuSection()
          + getHttpSessionUtil()
          + getOperatorAziendaId()
          + getSelectedAziendaId()
          + init()
          + isAziendaColumnShown()
          + isAziendaColumnShownInPage()
          + isAziendaSelectShown()
          + isQualsiasiAziendaDisabled()
          + setAziendaCount()
          + setAziendaService()
          + setAziendaViewModelList()
          + setCurrentMenuSection()
          + setHttpSessionUtil()
          + setOperatorAziendaId()
          + setSelectedAziendaId()
      }
    }
  }
  

  com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView .up.|> java.io.Serializable
  com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView o-- com.woonders.lacemscommon.service.AziendaService : aziendaService
  com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView o-- com.woonders.lacemsjsf.ui.AppMenuSection : currentMenuSection
  com.woonders.lacemsjsf.view.aziendaselection.AziendaSelectionView o-- com.woonders.lacemsjsf.util.HttpSessionUtil : httpSessionUtil


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
