@startuml

title __MEDIOLANUM's Class Diagram__\n

  namespace enumPdf {
    namespace mediolanum {
      enum PagesAllegatiA {
        ALLEGATO_A
        ALLEGATO_A1
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace mediolanum {
      enum PagesAllegatiAccessoInps {
        MODULO_INPS
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace mediolanum {
      enum PagesAllegatiB {
        ALLEGATO_B
        ALLEGATO_B1
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace mediolanum {
      enum PagesAllegatiCertificatoStipendio {
        CERTIFICATO_STIPENDIO
        DELEGA_RICHIESTA_CERTIFICATI
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace mediolanum {
      enum PagesAllegatiE {
        ALLEGATO_E_PAG1
        ALLEGATO_E_PAG2
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace mediolanum {
      enum PagesAllegatiNetB {
        CREDITO_NET_ALL_B
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace mediolanum {
      enum PagesAllegatiNetC {
        CREDITO_NET_C
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace mediolanum {
      enum PagesAllegatiRichiestaQuotaStipendio {
        MODULO_RICHIESTA
        page
      }
    }
  }
  

  namespace enumPdf {
    namespace mediolanum {
      enum PagesPrefinTfrMediolanum {
        AUTOCERTIFICA_TFR
        PAGINA_VUOTA_TFR
        page
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
