@startuml

title __MODEL's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace sms {
      namespace aws {
        namespace model {
          class com.woonders.lacemscommon.sms.aws.model.Delivery {
              ~ destination : String
              ~ dwellTimeMs : int
              ~ dwellTimeMsUntilDeviceAck : int
              ~ mcc : int
              ~ mnc : int
              ~ phoneCarrier : String
              ~ priceInUSD : double
              ~ providerResponse : String
              ~ smsType : String
              + Delivery()
              + Delivery()
              {static} + builder()
              + getDestination()
              + getDwellTimeMs()
              + getDwellTimeMsUntilDeviceAck()
              + getMcc()
              + getMnc()
              + getPhoneCarrier()
              + getPriceInUSD()
              + getProviderResponse()
              + getSmsType()
              + setDestination()
              + setDwellTimeMs()
              + setDwellTimeMsUntilDeviceAck()
              + setMcc()
              + setMnc()
              + setPhoneCarrier()
              + setPriceInUSD()
              + setProviderResponse()
              + setSmsType()
              + toString()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace sms {
      namespace aws {
        namespace model {
          class com.woonders.lacemscommon.sms.aws.model.Delivery.DeliveryBuilder {
              - destination : String
              - dwellTimeMs : int
              - dwellTimeMsUntilDeviceAck : int
              - mcc : int
              - mnc : int
              - phoneCarrier : String
              - priceInUSD : double
              - providerResponse : String
              - smsType : String
              + build()
              + destination()
              + dwellTimeMs()
              + dwellTimeMsUntilDeviceAck()
              + mcc()
              + mnc()
              + phoneCarrier()
              + priceInUSD()
              + providerResponse()
              + smsType()
              + toString()
              ~ DeliveryBuilder()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace sms {
      namespace aws {
        namespace model {
          class com.woonders.lacemscommon.sms.aws.model.Notification {
              ~ messageId : String
              ~ timestamp : String
              + Notification()
              + Notification()
              {static} + builder()
              + getMessageId()
              + getTimestamp()
              + setMessageId()
              + setTimestamp()
              + toString()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace sms {
      namespace aws {
        namespace model {
          class com.woonders.lacemscommon.sms.aws.model.Notification.NotificationBuilder {
              - messageId : String
              - timestamp : String
              + build()
              + messageId()
              + timestamp()
              + toString()
              ~ NotificationBuilder()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace sms {
      namespace aws {
        namespace model {
          class com.woonders.lacemscommon.sms.aws.model.SMSLog {
              ~ status : String
              + SMSLog()
              + SMSLog()
              {static} + builder()
              + getDelivery()
              + getNotification()
              + getStatus()
              + setDelivery()
              + setNotification()
              + setStatus()
              + toString()
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace sms {
      namespace aws {
        namespace model {
          class com.woonders.lacemscommon.sms.aws.model.SMSLog.SMSLogBuilder {
              - status : String
              + build()
              + delivery()
              + notification()
              + status()
              + toString()
              ~ SMSLogBuilder()
          }
        }
      }
    }
  }
  

  com.woonders.lacemscommon.sms.aws.model.Delivery +-down- com.woonders.lacemscommon.sms.aws.model.Delivery.DeliveryBuilder
  com.woonders.lacemscommon.sms.aws.model.Notification +-down- com.woonders.lacemscommon.sms.aws.model.Notification.NotificationBuilder
  com.woonders.lacemscommon.sms.aws.model.SMSLog o-- com.woonders.lacemscommon.sms.aws.model.Delivery : delivery
  com.woonders.lacemscommon.sms.aws.model.SMSLog o-- com.woonders.lacemscommon.sms.aws.model.Notification : notification
  com.woonders.lacemscommon.sms.aws.model.SMSLog +-down- com.woonders.lacemscommon.sms.aws.model.SMSLog.SMSLogBuilder
  com.woonders.lacemscommon.sms.aws.model.SMSLog.SMSLogBuilder o-- com.woonders.lacemscommon.sms.aws.model.Delivery : delivery
  com.woonders.lacemscommon.sms.aws.model.SMSLog.SMSLogBuilder o-- com.woonders.lacemscommon.sms.aws.model.Notification : notification


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
