@startuml

title __ENTITYENUM's Class Diagram__\n

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum AccountVersion {
            BASIC
            DEMO
            ENTERPRISE
            PROFESSIONAL
            STANDARD
            name
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum Assicurazioni {
            AVIVA
            AXA
            CARDIF
            CATTOLICA
            CREDIT
            ERGO
            GAIL
            HDI
            METLIFE
            NET
            VITTORIA
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum CatPensioni {
            ET
            SOCPDEL
            SO_VO
            VCOM
            VDAI
            VL
            VO
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum Corrispondenza {
            ALTRO
            DOMICILIO
            RESIDENZA
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum DurataPratica {
            DURATA_108
            DURATA_12
            DURATA_120
            DURATA_18
            DURATA_24
            DURATA_36
            DURATA_48
            DURATA_64
            DURATA_72
            DURATA_84
            DURATA_96
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum EsitoSmsNotificaLead {
            DA_SPEDIRE
            IN_SPEDIZIONE
            NON_RICEVUTO
            NON_SPEDITO
            NON_SPEDITO_CREDITO_INSUFFICIENTE
            NON_SPEDITO_DESTINATARIO_NON_VALIDO
            RICEVUTO
            SPEDITO
            SPEDIZIONE_DISABILITATA
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum FeeType {
            FIXED
            PERCENTAGE
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum FornitoreLead {
            DEVIS_PROX
            DIRECT_RESPONSE
            LEAD_LEADERS
            LEAD_STORE
            PAY_CLICK
            QUINTO_SUBITO
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum Impiego {
            AERONAUTICA
            ALTRO
            AUTONOMO
            CARABINIERE
            FINANZA
            MILITARE
            PARAPUBBLICO
            PENSIONATO
            POLIZIA
            PRIVATO
            PUBBLICO
            STATALE
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum Mensilita {
            MENSILITA_1
            MENSILITA_12
            MENSILITA_2
            MENSILITA_3
            MENSILITA_6
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum PreferenzaNumeroMittente {
            CELLULARE
            FISSO
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum Provenienza {
            AGENZIA
            BANCA
            CAMPAGNA_DA_FILE
            COLLABORATORE
            FACEBOOK
            LEAD
            WEB
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum RicaricaType {
            SMS_AGENZIA
            SMS_MARKETING
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum SimulatorRoundingMode {
            CLASSIC
            DOWN
            UP
            roundingMode
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum StatoCivile {
            CELIBE
            CONIUGATO
            DIVORZIATO
            NUBILE
            SEPARATO
            VEDOVO
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum StatoConteggioEstinzione {
            ATTESA_CONTEGGIO
            CONTEGGIO_RICEVUTO
            RICHIESTA_CONTEGGIO
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum StatoNominativo {
            APPUNTAMENTO_FISSATO
            ATTESA_DOC
            ATTESA_PREVENTIVO
            CONTESTATO
            CONTESTAZIONE_ACCETTATA
            CONTESTAZIONE_RIFIUTATA
            DA_LAVORARE
            DA_RICHIAMARE
            NON_ASSUMIBILE
            NON_FATTIBILE
            NON_INTERESSATO
            NON_RISPONDE
            NUMERO_INESISTENTE
            PREVENTIVO
            PREV_ACCETTATO
            RINNOVABILE
            TFR_NO
            VALUTAZIONE_ATC
            log
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum StatoPatrimoniale {
            COMUNIONE
            SEPARAZIONE
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum StatoPratica {
            AB
            ANNULATA
            APPROVATA
            ATTESA_CERTIFICATI_ALLEGATI
            DA_NOTIFICARE
            DECORRENZA
            DELIBERA
            ESTINTA
            IN_VALUTAZIONE
            ISTRUITA
            ISTRUTTORIA
            LIQUIDATA
            LIQUIDAZIONE
            NON_ISTRUITA
            PERFEZIONAMENTO
            POLIZZA
            PREACCETTAZIONE
            PREISTRUTTORIA
            RESPINTA
            TERMINATA
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum Tipo {
            CLIENTE
            NOMINATIVO
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum TipoAbitazione {
            AFFITTO
            PARENTI
            PROPRIETA
            TERZI
            value
          }
        }
      }
    }
  }
  

  namespace com.woonders.lacemscommon {
    namespace db {
      namespace entity {
        namespace num {
          enum ValutazioneCompagnia {
            NON_ASS
            PARAPUBBLICO
            PRIVATO
            PUBBLICO
            STATALE
            UNOCINQUE
            UNODUE
            UNOQUATTRO
            UNOTRE
            UNOUNO
            value
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
